=== icpc-sinchon/icpc-sinchon-workspace/libs/data/hallOfFame/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "title": "명예의 전당",
  "description": "신촌연합 알고리즘 캠프의 운영진, 기여자들을 기리는 명예의 전당 데이터 스키마",
  "properties": {
    "year": {
      "type": "integer",
      "description": "알고리즘 캠프가 진행된 연도",
      "minimum": 2019
    },
    "season": {
      "type": "string",
      "description": "알고리즘 캠프가 진행된 계절(여름, 겨울 중 하나)",
      "enum": ["Winter", "Summer"]
    },
    "duration": {
      "type": "string",
      "description": "알고리즘 캠프가 진행된 기간"
    },
    "president": {
      "type": "array",
      "description": "해당 시기의 회장(회장이 여러 명인 경우도 있음)",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "캠프 회장의 이름"
          },
          "school": {
            "type": "string",
            "description": "회장이 소속된 학교"
          },
          "role": {
            "type": "string",
            "description": "회장의 역할 표기(일반적으로 회장)"
          }
        },
        "required": ["name", "school", "role"],
        "additionalProperties": false
      }
    },
    "manager": {
      "type": "array",
      "description": "해당 시기의 운영진",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "운영진의 이름"
          },
          "school": {
            "type": "string",
            "description": "운영진이 소속된 학교"
          },
          "role": {
            "type": "string",
            "description": "운영진의 역할 표기"
          }
        },
        "required": ["name", "school", "role"],
        "additionalProperties": false
      }
    },
    "contributor": {
      "type": "array",
      "description": "기타 부분에서 캠프에 기여한 사람들",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "기여자의 이름"
          },
          "school": {
            "type": "string",
            "description": "기여자의 소속(꼭 학교는 아닐 수도 있음)"
          },
          "role": {
            "type": "string",
            "description": "기여자의 역할 표기"
          }
        },
        "required": ["name", "school", "role"],
        "additionalProperties": false
      }
    },
    "campContributor": {
      "type": "array",
      "description": "해당 시기의 알고리즘 캠프에 강사, 멘토 등으로 기여한 사람들",
      "items": {
        "type": "object",
        "properties": {
          "level": {
            "type": "string",
            "description": "캠프 난이도",
            "enum": ["초급", "중급", "고급"]
          },
          "lecturer": {
            "type": "array",
            "description": "알고리즘 캠프 강사 명단",
            "items": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string",
                  "description": "강사의 이름"
                },
                "school": {
                  "type": "string",
                  "description": "강사의 소속(꼭 학교는 아닐 수도 있음)"
                },
                "bojHandle": {
                  "type": "string",
                  "description": "강사의 BOJ 핸들"
                }
              },
              "required": ["name", "school", "bojHandle"],
              "additionalProperties": false
            }
          },
          "mentor": {
            "type": "array",
            "description": "알고리즘 캠프 멘토 명단",
            "items": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string",
                  "description": "멘토의 이름"
                },
                "school": {
                  "type": "string",
                  "description": "멘토의 소속(꼭 학교는 아닐 수도 있음)"
                },
                "bojHandle": {
                  "type": "string",
                  "description": "멘토의 BOJ 핸들"
                }
              },
              "required": ["name", "school", "bojHandle"],
              "additionalProperties": false
            }
          }
        },
        "required": ["level", "lecturer"],
        "additionalProperties": false
      }
    }
  },
  "required": ["year", "season", "duration", "manager", "campContributor"]
}

=== icpc-sinchon/icpc-sinchon-workspace/libs/data/hallOfFame/2023-Summer.json
{
  "$schema": "./schema.json",
  "year": 2023,
  "season": "Summer",
  "duration": "2023년 1학기 ~ 2023년 8월",
  "president": [
    {
      "name": "이성진",
      "school": "서강대학교",
      "role": "회장"
    },
    {
      "name": "이협",
      "school": "연세대학교",
      "role": "회장"
    }
  ],
  "manager": [
    {
      "name": "길수민",
      "school": "숙명여자대학교",
      "role": "운영진"
    },
    {
      "name": "김예송",
      "school": "홍익대학교",
      "role": "운영진"
    },
    {
      "name": "김정민",
      "school": "이화여자대학교",
      "role": "운영진"
    },
    {
      "name": "김정은",
      "school": "숙명여자대학교",
      "role": "운영진"
    },
    {
      "name": "노현근",
      "school": "홍익대학교",
      "role": "운영진"
    },
    {
      "name": "송상윤",
      "school": "연세대학교",
      "role": "운영진"
    },
    {
      "name": "정은채",
      "school": "이화여자대학교",
      "role": "운영진"
    },
    {
      "name": "조다니엘",
      "school": "서강대학교",
      "role": "운영진"
    },
    {
      "name": "조수아",
      "school": "이화여자대학교",
      "role": "운영진"
    }
  ],
  "campContributor": [
    {
      "level": "초급",
      "lecturer": [
        {
          "name": "박찬솔",
          "school": "숭실대학교",
          "bojHandle": "chansol"
        },
        {
          "name": "정회윤",
          "school": "서강대학교",
          "bojHandle": "yunny_world"
        }
      ],
      "mentor": [
        {
          "name": "김태윤",
          "school": "연세대학교",
          "bojHandle": "ystaeyoon113"
        },
        {
          "name": "이성진",
          "school": "서강대학교",
          "bojHandle": "moralbook"
        }
      ]
    },
    {
      "level": "중급",
      "lecturer": [
        {
          "name": "길수민",
          "school": "숙명여자대학교",
          "bojHandle": "2093ab"
        },
        {
          "name": "유호영",
          "school": "서강대학교",
          "bojHandle": "tkfkddl59323"
        },
        {
          "name": "최우현",
          "school": "연세대학교",
          "bojHandle": "starwh03"
        }
      ],
      "mentor": [
        {
          "name": "윤인섭",
          "school": "연세대학교",
          "bojHandle": "pinebananais"
        },
        {
          "name": "이협",
          "school": "연세대학교",
          "bojHandle": "dlguq0107"
        },
        {
          "name": "임지환",
          "school": "서강대학교",
          "bojHandle": "raararaara"
        }
      ]
    }
  ]
}

=== icpc-sinchon/icpc-sinchon-workspace/libs/data/hallOfFame/2023-Winter.json
{
  "$schema": "./schema.json",
  "year": 2023,
  "season": "Winter",
  "duration": "2022년 2학기 ~ 2023년 2월",
  "president": [
    {
      "name": "이가은",
      "school": "숙명여자대학교",
      "role": "회장"
    },
    {
      "name": "함윤주",
      "school": "홍익대학교",
      "role": "회장"
    }
  ],
  "manager": [
    {
      "name": "길수민",
      "school": "숙명여자대학교",
      "role": "운영진"
    },
    {
      "name": "노현근",
      "school": "홍익대학교",
      "role": "운영진"
    },
    {
      "name": "박주영",
      "school": "서강대학교",
      "role": "운영진"
    },
    {
      "name": "송상윤",
      "school": "연세대학교",
      "role": "운영진"
    },
    {
      "name": "이성진",
      "school": "서강대학교",
      "role": "운영진"
    },
    {
      "name": "이원주",
      "school": "이화여자대학교",
      "role": "운영진"
    },
    {
      "name": "이협",
      "school": "연세대학교",
      "role": "운영진"
    }
  ],
  "campContributor": [
    {
      "level": "초급",
      "lecturer": [
        {
          "name": "이지은",
          "school": "홍익대학교",
          "bojHandle": "leeju1013"
        },
        {
          "name": "함윤주",
          "school": "홍익대학교",
          "bojHandle": "ohhamma"
        }
      ],
      "mentor": [
        {
          "name": "길수민",
          "school": "숙명여자대학교",
          "bojHandle": "2093ab"
        },
        {
          "name": "권찬",
          "school": "홍익대학교",
          "bojHandle": "kckc0608"
        },
        {
          "name": "신유승",
          "school": "홍익대학교",
          "bojHandle": "boysoeng"
        }
      ]
    },
    {
      "level": "중급",
      "lecturer": [
        {
          "name": "유호영",
          "school": "서강대학교",
          "bojHandle": "tkfkddl59323"
        },
        {
          "name": "한상필",
          "school": "서강대학교",
          "bojHandle": "tksvlf123"
        }
      ],
      "mentor": [
        {
          "name": "이협",
          "school": "연세대학교",
          "bojHandle": "dlguq0107"
        },
        {
          "name": "정회윤",
          "school": "서강대학교",
          "bojHandle": "yunny_world"
        },
        {
          "name": "한승준",
          "school": "홍익대학교",
          "bojHandle": "dosawas"
        }
      ]
    }
  ]
}

=== icpc-sinchon/icpc-sinchon-workspace/libs/data/hallOfFame/2022-Summer.json
{
  "$schema": "./schema.json",
  "year": 2022,
  "season": "Summer",
  "duration": "2022년 1학기 ~ 2022년 8월",
  "president": [
    {
      "name": "김은서",
      "school": "이화여자대학교",
      "role": "회장"
    },
    {
      "name": "전지수",
      "school": "홍익대학교",
      "role": "회장"
    }
  ],
  "manager": [
    {
      "name": "이가은",
      "school": "숙명여자대학교",
      "role": "운영진"
    },
    {
      "name": "김가영",
      "school": "숙명여자대학교",
      "role": "운영진"
    },
    {
      "name": "박예나",
      "school": "숙명여자대학교",
      "role": "운영진"
    },
    {
      "name": "함윤주",
      "school": "홍익대학교",
      "role": "운영진"
    },
    {
      "name": "이원주",
      "school": "이화여자대학교",
      "role": "운영진"
    },
    {
      "name": "이재혁",
      "school": "서강대학교",
      "role": "운영진"
    },
    {
      "name": "유영서",
      "school": "연세대학교",
      "role": "운영진"
    }
  ],
  "campContributor": [
    {
      "level": "초급",
      "lecturer": [
        {
          "name": "김재헌",
          "school": "홍익대학교",
          "bojHandle": "xhdtlsid2"
        },
        {
          "name": "곽재혁",
          "school": "연세대학교",
          "bojHandle": "dreami63"
        }
      ],
      "mentor": [
        {
          "name": "김동건",
          "school": "서강대학교",
          "bojHandle": "dong_gas"
        },
        {
          "name": "이선주",
          "school": "홍익대학교",
          "bojHandle": "sunjoo9912"
        },
        {
          "name": "이지은",
          "school": "홍익대학교",
          "bojHandle": "leeju1013"
        },
        {
          "name": "한상필",
          "school": "서강대학교",
          "bojHandle": "tksvlf123"
        }
      ]
    },
    {
      "level": "중급",
      "lecturer": [
        {
          "name": "구재원",
          "school": "한양대학교",
          "bojHandle": "jjaewon9"
        },
        {
          "name": "나정휘",
          "school": "숭실대학교",
          "bojHandle": "jhnah917"
        }
      ]
    }
  ]
}

=== icpc-sinchon/icpc-sinchon-workspace/libs/data/hallOfFame/2024-Winter.json
{
  "$schema": "./schema.json",
  "year": 2024,
  "season": "Winter",
  "duration": "2023년 2학기 ~ 2024년 2월",
  "president": [
    {
      "name": "정은채",
      "school": "이화여자대학교",
      "role": "회장"
    },
    {
      "name": "조다니엘",
      "school": "서강대학교",
      "role": "회장"
    }
  ],
  "manager": [
    {
      "name": "김예송",
      "school": "홍익대학교",
      "role": "총무"
    },
    {
      "name": "김정은",
      "school": "숙명여자대학교",
      "role": "홍보팀장"
    },
    {
      "name": "김정민",
      "school": "이화여자대학교",
      "role": "홍보팀 운영진"
    },
    {
      "name": "박준영",
      "school": "서강대학교",
      "role": "홍보팀 운영진"
    },
    {
      "name": "이지언",
      "school": "연세대학교",
      "role": "홍보팀 운영진"
    },
    {
      "name": "천민재",
      "school": "홍익대학교",
      "role": "학생관리팀장"
    },
    {
      "name": "박경욱",
      "school": "연세대학교",
      "role": "학생관리팀 운영진"
    },
    {
      "name": "장희주",
      "school": "숙명여자대학교",
      "role": "학생관리팀 운영진"
    },
    {
      "name": "조수아",
      "school": "이화여자대학교",
      "role": "학생관리팀 운영진"
    }
  ],
  "contributor": [
    {
      "name": "김성현",
      "school": "서강대학교",
      "role": "프로그램관리팀장"
    },
    {
      "name": "길수민",
      "school": "숙명여자대학교",
      "role": "문제선정자"
    },
    {
      "name": "이국렬",
      "school": "연세대학교",
      "role": "문제선정자"
    },
    {
      "name": "임지환",
      "school": "서강대학교",
      "role": "문제선정자"
    },
    {
      "name": "노현근",
      "school": "홍익대학교",
      "role": "디자인팀"
    }
  ],
  "campContributor": [
    {
      "level": "초급",
      "lecturer": [
        {
          "name": "박찬솔",
          "school": "숭실대학교",
          "bojHandle": "chansol"
        },
        {
          "name": "채성우",
          "school": "서강대학교",
          "bojHandle": "lem0nad3"
        },
        {
          "name": "황채원",
          "school": "이화여자대학교",
          "bojHandle": "chaerryos"
        }
      ],
      "mentor": [
        {
          "name": "이성진",
          "school": "서강대학교",
          "bojHandle": "moralbook"
        },
        {
          "name": "이지언",
          "school": "연세대학교",
          "bojHandle": "ez_code"
        },
        {
          "name": "천민재",
          "school": "홍익대학교",
          "bojHandle": "open_mind"
        }
      ]
    },
    {
      "level": "중급",
      "lecturer": [
        {
          "name": "김건우",
          "school": "연세대학교",
          "bojHandle": "coconut99"
        },
        {
          "name": "김영현",
          "school": "서울대학교",
          "bojHandle": "kipa00"
        },
        {
          "name": "김태윤",
          "school": "연세대학교",
          "bojHandle": "ystaeyoon113"
        }
      ],
      "mentor": [
        {
          "name": "길수민",
          "school": "숙명여자대학교",
          "bojHandle": "2093ab"
        },
        {
          "name": "박경욱",
          "school": "연세대학교",
          "bojHandle": "sk091204091204"
        },
        {
          "name": "이협",
          "school": "연세대학교",
          "bojHandle": "dlguq0107"
        }
      ]
    }
  ]
}

=== icpc-sinchon/icpc-sinchon-workspace/libs/data/hallOfFame/2026-Summer.json
{
  "$schema": "./schema.json",
  "year": 2026,
  "season": "Summer",
  "duration": "2026년 1학기 ~ 2026년 8월",
  "president": [
    {
      "name": "윤지호",
      "school": "연세대학교",
      "role": "캠프장"
    },
    {
      "name": "정민규",
      "school": "홍익대학교",
      "role": "캠프장"
    }
  ],
  "manager": [
    {
      "name": "김규민",
      "school": "서강대학교",
      "role": "학생관리팀"
    },
    {
      "name": "김민서",
      "school": "연세대학교",
      "role": "대회관리팀"
    },
    {
      "name": "김은채",
      "school": "이화여자대학교",
      "role": "대회관리팀"
    },
    {
      "name": "류상겸",
      "school": "연세대학교",
      "role": "총무, 학생관리팀, 대회관리팀"
    },
    {
      "name": "오소정",
      "school": "이화여자대학교",
      "role": "학생관리팀, 디자인팀"
    },
    {
      "name": "오지우",
      "school": "이화여자대학교",
      "role": "디자인팀"
    },
    {
      "name": "이지은",
      "school": "숙명여자대학교",
      "role": "학생관리팀"
    },
    {
      "name": "이하늘",
      "school": "숙명여자대학교",
      "role": "대회관리팀"
    },
    {
      "name": "장주원",
      "school": "연세대학교",
      "role": "대회관리팀"
    }
  ],
  "campContributor": []
}

=== icpc-sinchon/icpc-sinchon-workspace/libs/data/hallOfFame/2025-Summer.json
{
  "$schema": "./schema.json",
  "year": 2025,
  "season": "Summer",
  "duration": "2025년 1학기 ~ 2025년 8월",
  "president": [
    {
      "name": "강호현",
      "school": "연세대학교",
      "role": "회장"
    },
    {
      "name": "이채은",
      "school": "숙명여자대학교",
      "role": "회장"
    }
  ],
  "manager": [
    {
      "name": "박지은",
      "school": "이화여자대학교",
      "role": "총무"
    },
    {
      "name": "허예진",
      "school": "홍익대학교",
      "role": "학생관리팀장"
    },
    {
      "name": "엄수현",
      "school": "이화여자대학교",
      "role": "학생관리팀"
    },
    {
      "name": "이하람",
      "school": "연세대학교",
      "role": "학생관리팀"
    },
    {
      "name": "오유림",
      "school": "연세대학교",
      "role": "학생관리팀"
    },
    {
      "name": "김태윤",
      "school": "서강대학교",
      "role": "홍보팀장"
    },
    {
      "name": "문채일",
      "school": "숙명여자대학교",
      "role": "홍보팀"
    },
    {
      "name": "안지선",
      "school": "홍익대학교",
      "role": "홍보팀"
    }
  ],
  "campContributor": []
}

=== icpc-sinchon/icpc-sinchon-workspace/libs/data/hallOfFame/2022-Winter.json
{
  "$schema": "./schema.json",
  "year": 2022,
  "season": "Winter",
  "duration": "2021년 2학기 ~ 2022년 2월",
  "president": [
    {
      "name": "권예빈",
      "school": "홍익대학교",
      "role": "회장"
    },
    {
      "name": "한다현",
      "school": "이화여자대학교",
      "role": "회장"
    }
  ],
  "manager": [
    {
      "name": "김가영",
      "school": "홍익대학교",
      "role": "운영진"
    },
    {
      "name": "김은서",
      "school": "이화여자대학교",
      "role": "운영진"
    },
    {
      "name": "박예나",
      "school": "숙명여자대학교",
      "role": "운영진"
    },
    {
      "name": "이재혁",
      "school": "서강대학교",
      "role": "운영진"
    },
    {
      "name": "전지수",
      "school": "홍익대학교",
      "role": "운영진"
    },
    {
      "name": "채정아",
      "school": "숙명여자대학교",
      "role": "운영진"
    }
  ],
  "campContributor": [
    {
      "level": "초급",
      "lecturer": [
        {
          "name": "김성현",
          "school": "서강대학교",
          "bojHandle": "dart"
        },
        {
          "name": "임지환",
          "school": "서강대학교",
          "bojHandle": "raararaara"
        }
      ],
      "mentor": [
        {
          "name": "권찬",
          "school": "홍익대학교",
          "bojHandle": "kckc0608"
        },
        {
          "name": "김동건",
          "school": "서강대학교",
          "bojHandle": "dong_gas"
        },
        {
          "name": "김서인",
          "school": "서강대학교",
          "bojHandle": "seoin0110"
        },
        {
          "name": "김성민",
          "school": "홍익대학교",
          "bojHandle": "tolelom"
        },
        {
          "name": "박준서",
          "school": "서강대학교",
          "bojHandle": "p_jun"
        },
        {
          "name": "한상필",
          "school": "서강대학교",
          "bojHandle": "tksvlf123"
        }
      ]
    },
    {
      "level": "중급",
      "lecturer": [
        {
          "name": "강효규",
          "school": "서강대학교",
          "bojHandle": "djs100201"
        }
      ],
      "mentor": [
        {
          "name": "김도현",
          "school": "홍익대학교",
          "bojHandle": "swoon"
        },
        {
          "name": "남유진",
          "school": "연세대학교",
          "bojHandle": "youx"
        },
        {
          "name": "조원빈",
          "school": "서강대학교",
          "bojHandle": "wbcho0504"
        }
      ]
    },
    {
      "level": "고급",
      "lecturer": [
        {
          "name": "이국렬",
          "school": "연세대학교",
          "bojHandle": "lky7674"
        },
        {
          "name": "전해성",
          "school": "서강대학교",
          "bojHandle": "seastar105"
        }
      ]
    }
  ]
}

=== icpc-sinchon/icpc-sinchon-workspace/libs/data/hallOfFame/2026-Winter.json
{
  "$schema": "./schema.json",
  "year": 2026,
  "season": "Winter",
  "duration": "2025년 2학기 ~ 2026년 2월",
  "president": [
    {
      "name": "이하람",
      "school": "연세대학교",
      "role": "캠프장"
    },
    {
      "name": "오유림",
      "school": "연세대학교",
      "role": "캠프장"
    }
  ],
  "manager": [
    {
      "name": "박시영",
      "school": "서강대학교",
      "role": "디자인팀, 총무팀"
    },
    {
      "name": "안지선",
      "school": "홍익대학교",
      "role": "홍보팀장"
    },
    {
      "name": "이하늘",
      "school": "숙명여자대학교",
      "role": "홍보팀"
    },
    {
      "name": "정민규",
      "school": "홍익대학교",
      "role": "디자인팀, 홍보팀"
    },
    {
      "name": "윤지호",
      "school": "연세대학교",
      "role": "홍보팀"
    },
    {
      "name": "김태윤",
      "school": "서강대학교",
      "role": "홍보팀"
    },
    {
      "name": "엄수현",
      "school": "이화여자대학교",
      "role": "학생관리팀장"
    },
    {
      "name": "이수진",
      "school": "이화여자대학교",
      "role": "디자인팀, 학생관리팀"
    },
    {
      "name": "류상겸",
      "school": "연세대학교",
      "role": "학생관리팀"
    },
    {
      "name": "노주환",
      "school": "서강대학교",
      "role": "프로그램관리팀, 학생관리팀"
    }
  ],
  "campContributor": []
}
