=== icpc-sinchon/icpc-sinchon-workspace/libs/data/hallOfFame/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "title": "명예의 전당",
  "description": "신촌연합 알고리즘 캠프의 운영진, 기여자들을 기리는 명예의 전당 데이터 스키마",
  "properties": {
    "year": {
      "type": "integer",
      "description": "알고리즘 캠프가 진행된 연도",
      "minimum": 2019
    },
    "season": {
      "type": "string",
      "description": "알고리즘 캠프가 진행된 계절(여름, 겨울 중 하나)",
      "enum": ["Winter", "Summer"]
    },
    "duration": {
      "type": "string",
      "description": "알고리즘 캠프가 진행된 기간"
    },
    "president": {
      "type": "array",
      "description": "해당 시기의 회장(회장이 여러 명인 경우도 있음)",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "캠프 회장의 이름"
          },
          "school": {
            "type": "string",
            "description": "회장이 소속된 학교"
          },
          "role": {
            "type": "string",
            "description": "회장의 역할 표기(일반적으로 회장)"
          }
        },
        "required": ["name", "school", "role"],
        "additionalProperties": false
      }
    },
    "manager": {
      "type": "array",
      "description": "해당 시기의 운영진",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "운영진의 이름"
          },
          "school": {
            "type": "string",
            "description": "운영진이 소속된 학교"
          },
          "role": {
            "type": "string",
            "description": "운영진의 역할 표기"
          }
        },
        "required": ["name", "school", "role"],
        "additionalProperties": false
      }
    },
    "contributor": {
      "type": "array",
      "description": "기타 부분에서 캠프에 기여한 사람들",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "기여자의 이름"
          },
          "school": {
            "type": "string",
            "description": "기여자의 소속(꼭 학교는 아닐 수도 있음)"
          },
          "role": {
            "type": "string",
            "description": "기여자의 역할 표기"
          }
        },
        "required": ["name", "school", "role"],
        "additionalProperties": false
      }
    },
    "campContributor": {
      "type": "array",
      "description": "해당 시기의 알고리즘 캠프에 강사, 멘토 등으로 기여한 사람들",
      "items": {
        "type": "object",
        "properties": {
          "level": {
            "type": "string",
            "description": "캠프 난이도",
            "enum": ["초급", "중급", "고급"]
          },
          "lecturer": {
            "type": "array",
            "description": "알고리즘 캠프 강사 명단",
            "items": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string",
                  "description": "강사의 이름"
                },
                "school": {
                  "type": "string",
                  "description": "강사의 소속(꼭 학교는 아닐 수도 있음)"
                },
                "bojHandle": {
                  "type": "string",
                  "description": "강사의 BOJ 핸들"
                }
              },
              "required": ["name", "school", "bojHandle"],
              "additionalProperties": false
            }
          },
          "mentor": {
            "type": "array",
            "description": "알고리즘 캠프 멘토 명단",
            "items": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string",
                  "description": "멘토의 이름"
                },
                "school": {
                  "type": "string",
                  "description": "멘토의 소속(꼭 학교는 아닐 수도 있음)"
                },
                "bojHandle": {
                  "type": "string",
                  "description": "멘토의 BOJ 핸들"
                }
              },
              "required": ["name", "school", "bojHandle"],
              "additionalProperties": false
            }
          }
        },
        "required": ["level", "lecturer"],
        "additionalProperties": false
      }
    }
  },
  "required": ["year", "season", "duration", "manager", "campContributor"]
}

=== icpc-sinchon/icpc-sinchon-workspace/libs/data/hallOfFame/2024-Summer.json
{
  "$schema": "./schema.json",
  "year": 2024,
  "season": "Summer",
  "duration": "2024년 1학기 ~ 2024년 8월",
  "president": [
    {
      "name": "이지언",
      "school": "연세대학교",
      "role": "회장"
    },
    {
      "name": "천민재",
      "school": "홍익대학교",
      "role": "회장"
    }
  ],
  "manager": [
    {
      "name": "김예송",
      "school": "홍익대학교",
      "role": "총무"
    },
    {
      "name": "신정화",
      "school": "이화여자대학교",
      "role": "홍보팀장"
    },
    {
      "name": "최연재",
      "school": "숙명여자대학교",
      "role": "홍보팀"
    },
    {
      "name": "홍서희",
      "school": "숙명여자대학교",
      "role": "홍보팀"
    },
    {
      "name": "황채원",
      "school": "이화여자대학교",
      "role": "홍보팀"
    },
    {
      "name": "박준영",
      "school": "서강대학교",
      "role": "홍보팀"
    },
    {
      "name": "김지호",
      "school": "연세대학교",
      "role": "홍보팀"
    },
    {
      "name": "장희주",
      "school": "숙명여자대학교",
      "role": "학생관리팀장"
    },
    {
      "name": "이재찬",
      "school": "서강대학교",
      "role": "학생관리팀"
    },
    {
      "name": "한유리",
      "school": "이화여자대학교",
      "role": "학생관리팀"
    },
    {
      "name": "박경욱",
      "school": "연세대학교",
      "role": "학생관리팀"
    },
    {
      "name": "서채연",
      "school": "홍익대학교",
      "role": "학생관리팀"
    }
  ],
  "contributor": [
    {
      "name": "김성현",
      "school": "서강대학교",
      "role": "프로그램관리팀장"
    },
    {
      "name": "전우제",
      "school": "연세대학교",
      "role": "프로그램관리팀 용병"
    },
    {
      "name": "정은채",
      "school": "이화여자대학교",
      "role": "디자인팀 용병"
    },
    {
      "name": "김영현",
      "school": "서울대학교",
      "role": "문제선정자"
    },
    {
      "name": "박진한",
      "school": "고려대학교",
      "role": "문제선정자"
    },
    {
      "name": "이국렬",
      "school": "연세대학교",
      "role": "문제선정자"
    }
  ],
  "campContributor": [
    {
      "level": "초급",
      "lecturer": [
        {
          "name": "박찬솔",
          "school": "숭실대학교",
          "bojHandle": "chansol"
        },
        {
          "name": "김지호",
          "school": "연세대학교",
          "bojHandle": "wlgh7407"
        }
      ],
      "mentor": [
        {
          "name": "최연재",
          "school": "숙명여자대학교",
          "bojHandle": "0yeonjae2"
        },
        {
          "name": "전우제",
          "school": "연세대학교",
          "bojHandle": "kiwiyou"
        }
      ]
    },
    {
      "level": "중급",
      "lecturer": [
        {
          "name": "김영현",
          "school": "서울대학교",
          "bojHandle": "kipa00"
        },
        {
          "name": "박진한",
          "school": "고려대학교",
          "bojHandle": "jinhan814"
        }
      ],
      "mentor": [
        {
          "name": "이재찬",
          "school": "서강대학교",
          "bojHandle": "dlwocks1209"
        },
        {
          "name": "김건우",
          "school": "연세대학교",
          "bojHandle": "coconut99"
        }
      ]
    }
  ]
}

=== icpc-sinchon/icpc-sinchon-workspace/libs/data/hallOfFame/2020 Summer.json
{
  "$schema": "./schema.json",
  "year": 2020,
  "season": "Summer",
  "duration": "2020년 1학기 ~ 2020년 8월",
  "manager": [
    {
      "name": "임지환",
      "school": "서강대학교",
      "role": "임원진"
    },
    {
      "name": "이재열",
      "school": "홍익대학교",
      "role": "임원진"
    },
    {
      "name": "이국렬",
      "school": "연세대학교",
      "role": "임원진"
    },
    {
      "name": "고민재",
      "school": "홍익대학교",
      "role": "임원진"
    },
    {
      "name": "반보영",
      "school": "홍익대학교",
      "role": "임원진"
    },
    {
      "name": "김예은",
      "school": "이화여자대학교",
      "role": "임원진"
    },
    {
      "name": "남수연",
      "school": "숙명여자대학교",
      "role": "운영 보조"
    },
    {
      "name": "김경근",
      "school": "홍익대학교",
      "role": "운영 보조"
    }
  ],
  "campContributor": [
    {
      "level": "초급",
      "lecturer": [
        {
          "name": "배철환",
          "school": "서강대",
          "bojHandle": "bcc0830"
        },
        {
          "name": "백성익",
          "school": "홍익대",
          "bojHandle": "906bc"
        }
      ]
    },
    {
      "level": "중급",
      "lecturer": [
        {
          "name": "윤인섭",
          "school": "연세대",
          "bojHandle": "pinebananais"
        },
        {
          "name": "이준석",
          "school": "서강대",
          "bojHandle": "semteo04"
        }
      ]
    },
    {
      "level": "고급",
      "lecturer": [
        {
          "name": "전해성",
          "school": "서강대",
          "bojHandle": "seastar105"
        }
      ]
    }
  ]
}

=== icpc-sinchon/icpc-sinchon-workspace/libs/data/hallOfFame/2025-Winter.json
{
  "$schema": "./schema.json",
  "year": 2025,
  "season": "Winter",
  "duration": "2024년 2학기 ~ 2025년 2월",
  "president": [
    {
      "name": "최연재",
      "school": "숙명여자대학교",
      "role": "회장"
    },
    {
      "name": "서채연",
      "school": "홍익대학교",
      "role": "회장"
    }
  ],
  "manager": [
    {
      "name": "신정화",
      "school": "이화여자대학교",
      "role": "총무"
    },
    {
      "name": "홍서희",
      "school": "숙명여자대학교",
      "role": "홍보팀장"
    },
    {
      "name": "김지호",
      "school": "연세대학교",
      "role": "홍보팀"
    },
    {
      "name": "황채원",
      "school": "이화여자대학교",
      "role": "홍보팀"
    },
    {
      "name": "김태윤",
      "school": "서강대학교",
      "role": "홍보팀"
    },
    {
      "name": "허예진",
      "school": "홍익대학교",
      "role": "홍보팀"
    },
    {
      "name": "이재찬",
      "school": "서강대학교",
      "role": "학생관리팀장"
    },
    {
      "name": "한유리",
      "school": "이화여자대학교",
      "role": "학생관리팀"
    },
    {
      "name": "박지은",
      "school": "이화여자대학교",
      "role": "학생관리팀"
    },
    {
      "name": "이채은",
      "school": "숙명여자대학교",
      "role": "학생관리팀"
    },
    {
      "name": "강호현",
      "school": "연세대학교",
      "role": "학생관리팀"
    }
  ],
  "campContributor": []
}

=== icpc-sinchon/icpc-sinchon-workspace/libs/data/hallOfFame/2020 Winter.json
{
  "$schema": "./schema.json",
  "year": 2020,
  "season": "Winter",
  "duration": "2019년 2학기 ~ 2020년 2월",
  "manager": [
    {
      "name": "임지환",
      "school": "서강대학교",
      "role": "임원진"
    },
    {
      "name": "이재열",
      "school": "홍익대학교",
      "role": "임원진"
    },
    {
      "name": "박수현",
      "school": "서강대학교",
      "role": "임원진"
    }
  ],
  "campContributor": [
    {
      "level": "초급",
      "lecturer": [
        {
          "name": "이태한",
          "school": "서강대",
          "bojHandle": "sogangcse"
        },
        {
          "name": "이재열",
          "school": "홍익대",
          "bojHandle": "malkoring"
        },
        {
          "name": "김성민",
          "school": "홍익대",
          "bojHandle": "tolelom"
        }
      ]
    },
    {
      "level": "중급",
      "lecturer": [
        {
          "name": "임지환",
          "school": "서강대",
          "bojHandle": "raararaara"
        },
        {
          "name": "이기현",
          "school": "서강대",
          "bojHandle": "sbrus_1213"
        }
      ]
    },
    {
      "level": "고급",
      "lecturer": [
        {
          "name": "박수현",
          "school": "서강대",
          "bojHandle": "shiftpsh"
        },
        {
          "name": "이상원",
          "school": "서강대",
          "bojHandle": "gumgood"
        }
      ]
    }
  ]
}

=== icpc-sinchon/icpc-sinchon-workspace/libs/data/hallOfFame/2021-Winter.json
{
  "$schema": "./schema.json",
  "year": 2021,
  "season": "Winter",
  "duration": "2020년 2학기 ~ 2021년 2월",
  "president": [
    {
      "name": "김도은",
      "school": "숙명여자대학교",
      "role": "회장"
    }
  ],
  "manager": [
    {
      "name": "남수연",
      "school": "숙명여자대학교",
      "role": "임원진"
    },
    {
      "name": "김도현",
      "school": "홍익대학교",
      "role": "임원진"
    },
    {
      "name": "이동주",
      "school": "서강대학교",
      "role": "임원진"
    },
    {
      "name": "김경근",
      "school": "홍익대학교",
      "role": "임원진"
    },
    {
      "name": "강효규",
      "school": "서강대학교",
      "role": "임원진"
    },
    {
      "name": "홍재령",
      "school": "이화여자대학교",
      "role": "임원진"
    },
    {
      "name": "이국렬",
      "school": "연세대학교",
      "role": "임원진"
    }
  ],
  "campContributor": [
    {
      "level": "초급",
      "lecturer": [
        {
          "name": "강효규",
          "school": "서강대학교",
          "bojHandle": "djs100201"
        },
        {
          "name": "김기선",
          "school": "홍익대학교",
          "bojHandle": "xkdlaldtjfnl"
        }
      ],
      "mentor": [
        {
          "name": "박재형",
          "school": "서강대학교",
          "bojHandle": "pjh6792"
        },
        {
          "name": "고민재",
          "school": "홍익대학교",
          "bojHandle": "minjae705"
        },
        {
          "name": "김성현",
          "school": "서강대학교",
          "bojHandle": "dart"
        },
        {
          "name": "박건",
          "school": "서강대학교",
          "bojHandle": "jkroll87"
        },
        {
          "name": "박장성",
          "school": "홍익대학교",
          "bojHandle": "kimchist"
        },
        {
          "name": "권찬",
          "school": "홍익대학교",
          "bojHandle": "kckc0608"
        },
        {
          "name": "박원",
          "school": "UNIST",
          "bojHandle": "chunghan"
        },
        {
          "name": "박선종",
          "school": "연세대학교",
          "bojHandle": "standingbell"
        },
        {
          "name": "이민희",
          "school": "서강대학교",
          "bojHandle": "minigimbob"
        }
      ]
    },
    {
      "level": "중급",
      "lecturer": [
        {
          "name": "윤인섭",
          "school": "연세대학교",
          "bojHandle": "pinebananais"
        },
        {
          "name": "한동규",
          "school": "UNIST",
          "bojHandle": "queued_q"
        }
      ],
      "mentor": [
        {
          "name": "조원빈",
          "school": "서강대학교",
          "bojHandle": "wbcho0504"
        },
        {
          "name": "이윤제",
          "school": "서강대학교",
          "bojHandle": "yjyj1027"
        },
        {
          "name": "윤이빈",
          "school": "숙명여자대학교",
          "bojHandle": "yibin99"
        }
      ]
    },
    {
      "level": "고급",
      "lecturer": [
        {
          "name": "전해성",
          "school": "서강대학교",
          "bojHandle": "seastar105"
        },
        {
          "name": "이국렬",
          "school": "연세대학교",
          "bojHandle": "lky7674"
        }
      ],
      "mentor": [
        {
          "name": "이상원",
          "school": "서강대학교",
          "bojHandle": "gumgood"
        }
      ]
    }
  ]
}
