=== icpc-sinchon/icpc-sinchon-workspace/libs/data/suapc/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "title": "SUAPC",
  "description": "신촌지역 대학교 프로그래밍 동아리 연합대회 기록을 담은 데이터 스키마",
  "definitions": {
    "person": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "이름"
        },
        "school": {
          "type": "string",
          "description": "소속 학교"
        },
        "bojHandle": {
          "type": "string",
          "description": "BOJ 아이디"
        }
      },
      "required": ["name", "school", "bojHandle"]
    },
    "sponsor": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "후원사 ID"
        },
        "name": {
          "type": "string",
          "description": "후원 이름"
        },
        "note": {
          "type": "array",
          "description": "후원 관련 기록",
          "items": {
            "type": "string"
          }
        }
      },
      "required": ["id", "name"]
    }
  },
  "properties": {
    "year": {
      "type": "integer",
      "description": "연합 대회가 진행된 연도",
      "minimum": 2019
    },
    "season": {
      "type": "string",
      "description": "연합 대회가 진행된 계절(여름, 겨울 중 하나)",
      "enum": ["Winter", "Summer"]
    },
    "dateTime": {
      "type": "string",
      "description": "연합 대회가 진행된 날짜와 시간"
    },
    "note": {
      "type": "string",
      "description": "대회에 관련된 사항. 이때 특별했던 시기적 이슈 등을 기록"
    },
    "links": {
      "type": "object",
      "description": "연합 대회 관련 링크",
      "properties": {
        "problemBojLink": {
          "type": "string",
          "description": "캠프 콘테스트의 문제 BOJ 링크"
        },
        "problemPdf": {
          "type": "string",
          "description": "캠프 콘테스트의 문제 PDF 링크"
        },
        "solutionPdf": {
          "type": "string",
          "description": "캠프 콘테스트의 솔루션 PDF 링크"
        },
        "scoreboard": {
          "type": "array",
          "description": "캠프 콘테스트의 스코어보드 링크들. div1, div2가 있던 시절을 대비해 배열로 처리",
          "items": {
            "type": "string",
            "description": "캠프 콘테스트의 스코어보드 링크"
          },
          "minItems": 1,
          "maxItems": 3
        },
        "posterImage": {
          "type": "string",
          "description": "연합 대회의 공식 포스터 이미지 링크"
        }
      }
    },
    "contest": {
      "type": "array",
      "description": "SUAPC 대회 목록",
      "items": {
        "$ref": "./contest.json#/definitions/contest"
      }
    },
    "setter": {
      "type": "array",
      "description": "SUAPC 문제 출제자",
      "items": {
        "$ref": "#/definitions/person"
      }
    },
    "reviewer": {
      "type": "array",
      "description": "SUAPC 문제 검수자",
      "items": {
        "$ref": "#/definitions/person"
      }
    },
    "sponsor": {
      "type": "array",
      "description": "SUAPC 후원사",
      "items": {
        "$ref": "#/definitions/sponsor"
      }
    },
    "personalSponsor": {
      "type": "array",
      "description": "SUAPC의 개인 후원자",
      "items": {
        "$ref": "#/definitions/sponsor"
      }
    }
  },
  "required": [
    "year",
    "season",
    "dateTime",
    "links",
    "contest",
    "setter",
    "reviewer",
    "sponsor"
  ]
}

=== icpc-sinchon/icpc-sinchon-workspace/libs/data/suapc/2024-Winter.json
{
  "$schema": "./schema.json",
  "year": 2024,
  "season": "Winter",
  "dateTime": "2024년 2월 17일(토) 오후 12시 ~ 오후 5시",
  "note": "",
  "links": {
    "problemBojLink": "https://www.acmicpc.net/category/detail/4149",
    "solutionPdf": "SUAPC_2024_Winter_Solution.pdf",
    "scoreboard": ["https://www.acmicpc.net/contest/spotboard/1237"],
    "posterImage": "SUAPC_2024w_Poster.jpeg"
  },
  "contest": [
    {
      "contestName": null,
      "awards": [
        {
          "rank": 1,
          "solved": 11,
          "teamName": "AKARAKA",
          "school": "연세대학교",
          "member": ["김태윤", "정용진", "김건우"]
        },
        {
          "rank": 2,
          "solved": 9,
          "teamName": "goraani",
          "school": "서강대학교",
          "member": ["김동건", "조원빈", "강효규"]
        },
        {
          "rank": 3,
          "solved": 9,
          "teamName": "Raa_FanClub",
          "school": "서강대학교",
          "member": ["송근수", "이승형", "박성준"]
        },
        {
          "rank": 4,
          "solved": 9,
          "teamName": "입대 전 라스트댄스",
          "school": "연세대학교",
          "member": ["이협", "이도훈", "최우현"]
        },
        {
          "rank": 5,
          "solved": 8,
          "teamName": "진짜1등하러왔습니다",
          "school": "연세대학교",
          "member": ["곽재혁", "김형진", "박경욱"]
        },
        {
          "rank": 6,
          "solved": 8,
          "teamName": "돈비고고",
          "school": "연세대학교",
          "member": ["장현우", "김지호", "최원준"]
        },
        {
          "rank": 7,
          "solved": 8,
          "teamName": "가지오이당근",
          "school": "연세대학교",
          "member": ["한의엽", "전우제", "이지언"]
        },
        {
          "rank": 8,
          "solved": 8,
          "teamName": "병공병",
          "school": "홍익대학교",
          "member": ["정재현", "김도현", "김재헌"]
        },
        {
          "rank": 9,
          "solved": 8,
          "teamName": "기령손",
          "school": "서강대학교",
          "member": ["손기령", "김서인", "이하윤"]
        },
        {
          "rank": 10,
          "solved": 8,
          "teamName": "홍하예프",
          "school": "홍익대학교",
          "member": ["전승민", "한승준", "심동현"]
        }
      ],
      "problemList": [
        {
          "problemTitle": "가상 검증 기술",
          "link": "https://www.acmicpc.net/problem/31416",
          "setter": {
            "name": "유상혁",
            "school": "아주대학교",
            "bojHandle": "golazcc83"
          }
        },
        {
          "problemTitle": "가장 짧은 높이",
          "link": "https://www.acmicpc.net/problem/31417",
          "setter": {
            "name": "현지훈",
            "school": "KAIST",
            "bojHandle": "qawbecrdtey"
          }
        },
        {
          "problemTitle": "스펀지",
          "link": "https://www.acmicpc.net/problem/31418",
          "setter": {
            "name": "이지훈",
            "school": "서강대학교",
            "bojHandle": "maker29"
          }
        },
        {
          "problemTitle": "배열 제작의 달인",
          "link": "https://www.acmicpc.net/problem/31419",
          "setter": {
            "name": "김규진",
            "school": "액션파워",
            "bojHandle": "snrnsidy"
          }
        },
        {
          "problemTitle": "문자열 - 그래프 매칭",
          "link": "https://www.acmicpc.net/problem/31420",
          "setter": {
            "name": "유호영",
            "school": "서강대학교",
            "bojHandle": "tkfkddl59323"
          }
        },
        {
          "problemTitle": "호떡 뒤집기",
          "link": "https://www.acmicpc.net/problem/31421",
          "setter": {
            "name": "임예준",
            "school": "한국과학영재학교",
            "bojHandle": "edward3378"
          }
        },
        {
          "problemTitle": "AND, OR, XOR 2",
          "link": "https://www.acmicpc.net/problem/31422",
          "setter": {
            "name": "장래오",
            "school": "포항공과대학교",
            "bojHandle": "leo020630"
          }
        },
        {
          "problemTitle": "신촌 통폐합 계획",
          "link": "https://www.acmicpc.net/problem/31423",
          "setter": {
            "name": "박진한",
            "school": "고려대학교",
            "bojHandle": "jinhan814"
          }
        },
        {
          "problemTitle": "최대공약수 게임",
          "link": "https://www.acmicpc.net/problem/31424",
          "setter": {
            "name": "유상혁",
            "school": "아주대학교",
            "bojHandle": "golazcc83"
          }
        },
        {
          "problemTitle": "토지 판매",
          "link": "https://www.acmicpc.net/problem/31425",
          "setter": {
            "name": "장래오",
            "school": "포항공과대학교",
            "bojHandle": "leo020630"
          }
        },
        {
          "problemTitle": "신촌방위본부: 지하벙커의 비밀",
          "link": "https://www.acmicpc.net/problem/31426",
          "setter": {
            "name": "김도훈",
            "school": "한양대학교",
            "bojHandle": "dohoon"
          }
        },
        {
          "problemTitle": "신촌 도로망 관리와 쿼리",
          "link": "https://www.acmicpc.net/problem/31427",
          "setter": {
            "name": "노현제",
            "school": "서울과학기술대학교",
            "bojHandle": "hjroh0315"
          }
        },
        {
          "problemTitle": "엘리스 트랙 매칭",
          "link": "https://www.acmicpc.net/problem/31428",
          "setter": {
            "name": "조다니엘",
            "school": "서강대학교",
            "bojHandle": "arduinocc04"
          }
        }
      ]
    }
  ],
  "setter": [
    {
      "name": "노현제",
      "school": "서울과학기술대학교",
      "bojHandle": "hjroh0315"
    },
    {
      "name": "장래오",
      "school": "포항공과대학교",
      "bojHandle": "leo020630"
    },
    {
      "name": "박진한",
      "school": "고려대학교",
      "bojHandle": "jinhan814"
    },
    {
      "name": "이지훈",
      "school": "서강대학교",
      "bojHandle": "maker29"
    },
    {
      "name": "임예준",
      "school": "한국과학영재학교",
      "bojHandle": "edward3378"
    },
    {
      "name": "김도훈",
      "school": "한양대학교",
      "bojHandle": "dohoon"
    },
    {
      "name": "전형록",
      "school": "경북대학교",
      "bojHandle": "exqt"
    },
    {
      "name": "유상혁",
      "school": "아주대학교",
      "bojHandle": "golazcc83"
    },
    {
      "name": "김규진",
      "school": "액션파워",
      "bojHandle": "snrnsidy"
    },
    {
      "name": "현지훈",
      "school": "KAIST",
      "bojHandle": "qawbecrdtey"
    },
    {
      "name": "유호영",
      "school": "서강대학교",
      "bojHandle": "tkfkddl59323"
    }
  ],
  "reviewer": [
    {
      "name": "이국렬",
      "school": "연세대학교",
      "bojHandle": "lky7674"
    },
    {
      "name": "정우경",
      "school": "전북대학교",
      "bojHandle": "man_of_learning"
    },
    {
      "name": "강희원",
      "school": "서울대학교",
      "bojHandle": "heeda0528"
    },
    {
      "name": "문정후",
      "school": "경기과학고등학교",
      "bojHandle": "mjhmjh1104"
    },
    {
      "name": "박진식",
      "school": "클루미오",
      "bojHandle": "pjshwa"
    },
    {
      "name": "조상렬",
      "school": "서울대학교",
      "bojHandle": "whqkrkt04"
    },
    {
      "name": "白崎杏子(cologne)",
      "school": "開拓団訓練所",
      "bojHandle": "cologne"
    }
  ],
  "sponsor": [
    {
      "id": "autoever",
      "name": "현대오토에버"
    },
    {
      "id": "hanbit",
      "name": "한빛미디어"
    },
    {
      "id": "youngjin",
      "name": "영진닷컴"
    },
    {
      "id": "j&s",
      "name": "J&S factory"
    },
    {
      "id": "shinhands",
      "name": "신한 DS"
    },
    {
      "id": "solvedac",
      "name": "솔브드"
    },
    {
      "id": "multiply",
      "name": "멀티플라이"
    },
    {
      "id": "goorm",
      "name": "구름"
    },
    {
      "id": "startlink",
      "name": "스타트링크"
    },
    {
      "id": "elice",
      "name": "엘리스"
    }
  ],
  "personalSponsor": [
    {
      "id": "이재열",
      "name": "이재열"
    },
    {
      "id": "pjshwa",
      "name": "pjshwa"
    },
    {
      "id": "신촌고라니",
      "name": "신촌고라니"
    },
    {
      "id": "천민재",
      "name": "천민재"
    },
    {
      "id": "킹갓캠프장정은채",
      "name": "킹갓캠프장정은채"
    },
    {
      "id": "풀스택해커인공지능PS킹캣박경욱",
      "name": "풀스택해커인공지능PS킹캣박경욱"
    },
    {
      "id": "정은체",
      "name": "정은체"
    }
  ]
}

=== icpc-sinchon/icpc-sinchon-workspace/libs/data/suapc/2021-Winter.json
{
  "$schema": "./schema.json",
  "year": 2021,
  "season": "Winter",
  "dateTime": "2021년 2월 28일 오후 12시 ~ 오후 5시",
  "note": "",
  "links": {
    "problemBojLink": "https://www.acmicpc.net/category/detail/2446",
    "problemPdf": "SUAPC_2021w_Problem.pdf",
    "solutionPdf": "SUAPC_2021w_Solution.pdf",
    "scoreboard": ["https://www.acmicpc.net/contest/spotboard/586"],
    "posterImage": "SUAPC_2021w_Poster.png"
  },
  "contest": [
    {
      "contestName": null,
      "awards": [
        {
          "rank": 1,
          "solved": 12,
          "teamName": "Supported by LKY",
          "school": "연세대학교",
          "member": ["윤인섭", "황준호", "남현우"]
        },
        {
          "rank": 2,
          "solved": 9,
          "teamName": "151719",
          "school": "서강대학교",
          "member": ["전해성", "정재훈", "이준석"]
        },
        {
          "rank": 3,
          "solved": 9,
          "teamName": "NO ORANGE CANT WIN",
          "school": "서강대학교",
          "member": ["김관우", "박재형", "이윤제"]
        },
        {
          "rank": 4,
          "solved": 8,
          "teamName": "TERRA",
          "school": "서강대학교",
          "member": ["이동주", "이민희", "조원빈"]
        },
        {
          "rank": 5,
          "solved": 8,
          "teamName": "팬케이크맛 쿠키",
          "school": "연세대학교",
          "member": ["박선종", "김태윤", "김민재"]
        },
        {
          "rank": 6,
          "solved": 7,
          "teamName": "APP",
          "school": "서강대학교",
          "member": ["강문해", "강다혜", "전민수"]
        },
        {
          "rank": 7,
          "solved": 7,
          "teamName": "전생했더니 박건이었던 건에 대하여",
          "school": "서강대학교",
          "member": ["강효규", "박건", "손기령"]
        },
        {
          "rank": 8,
          "solved": 6,
          "teamName": "서수삼",
          "school": "서강대학교",
          "member": ["홍서준", "유호영", "오재석"]
        },
        {
          "rank": 9,
          "solved": 6,
          "teamName": "동동박",
          "school": "연세대학교",
          "member": ["권동욱", "동용훈", "박영한"]
        },
        {
          "rank": 10,
          "solved": 6,
          "teamName": "상금타서소고기사먹자",
          "school": "홍익대학교",
          "member": ["정윤석", "김종욱", "서영진"]
        }
      ],
      "problemList": [
        {
          "problemTitle": "우선순위 계산기",
          "link": "https://www.acmicpc.net/problem/20936",
          "setter": {
            "name": "이국렬",
            "school": "연세대학교",
            "bojHandle": "lky7674"
          }
        },
        {
          "problemTitle": "떡국",
          "link": "https://www.acmicpc.net/problem/20937",
          "setter": {
            "name": "이상원",
            "school": "서강대학교",
            "bojHandle": "gumgood"
          }
        },
        {
          "problemTitle": "반짝반짝",
          "link": "https://www.acmicpc.net/problem/20938",
          "setter": {
            "name": "박수현",
            "school": "서강대학교",
            "bojHandle": "shiftpsh"
          }
        },
        {
          "problemTitle": "달고나",
          "link": "https://www.acmicpc.net/problem/20939",
          "setter": {
            "name": "이상원",
            "school": "서강대학교",
            "bojHandle": "gumgood"
          }
        },
        {
          "problemTitle": "시철이가 사랑한 수식",
          "link": "https://www.acmicpc.net/problem/20940",
          "setter": {
            "name": "정기웅",
            "school": "연세대학교",
            "bojHandle": "QuqqU"
          }
        },
        {
          "problemTitle": "성싶당",
          "link": "https://www.acmicpc.net/problem/20941",
          "setter": {
            "name": "박수현",
            "school": "서강대학교",
            "bojHandle": "shiftpsh"
          }
        },
        {
          "problemTitle": "신촌지역 초중고등학생 프로그래밍 대회 동아리 연합 대회",
          "link": "https://www.acmicpc.net/problem/20942",
          "setter": {
            "name": "정연두",
            "school": "홍익대학교",
            "bojHandle": "Green55"
          }
        },
        {
          "problemTitle": "카카오톡",
          "link": "https://www.acmicpc.net/problem/20943",
          "setter": {
            "name": "이국렬",
            "school": "연세대학교",
            "bojHandle": "lky7674"
          }
        },
        {
          "problemTitle": "팰린드롬 척화비",
          "link": "https://www.acmicpc.net/problem/20944",
          "setter": {
            "name": "정기웅",
            "school": "연세대학교",
            "bojHandle": "QuqqU"
          }
        },
        {
          "problemTitle": "의자 게임",
          "link": "https://www.acmicpc.net/problem/20945",
          "setter": {
            "name": "정연두",
            "school": "홍익대학교",
            "bojHandle": "Green55"
          }
        },
        {
          "problemTitle": "합성인수분해",
          "link": "https://www.acmicpc.net/problem/20946",
          "setter": {
            "name": "정연두",
            "school": "홍익대학교",
            "bojHandle": "Green55"
          }
        },
        {
          "problemTitle": "습격받은 도시",
          "link": "https://www.acmicpc.net/problem/20947",
          "setter": {
            "name": "이상원",
            "school": "서강대학교",
            "bojHandle": "gumgood"
          }
        },
        {
          "problemTitle": "Go와 함께하는 전화망 서비스",
          "link": "https://www.acmicpc.net/problem/20948",
          "setter": {
            "name": "이국렬",
            "school": "연세대학교",
            "bojHandle": "lky7674"
          }
        }
      ]
    }
  ],
  "setter": [
    {
      "name": "이국렬",
      "school": "연세대학교",
      "bojHandle": "lky7674"
    },
    {
      "name": "정연두",
      "school": "홍익대학교",
      "bojHandle": "Green55"
    },
    {
      "name": "박수현",
      "school": "서강대학교",
      "bojHandle": "shiftpsh"
    },
    {
      "name": "정기웅",
      "school": "연세대학교",
      "bojHandle": "QuqqU"
    },
    {
      "name": "이상원",
      "school": "서강대학교",
      "bojHandle": "gumgood"
    }
  ],
  "reviewer": [
    {
      "name": "최재민",
      "school": "KAIST",
      "bojHandle": "jh05013"
    },
    {
      "name": "조경완",
      "school": "숭실대학교",
      "bojHandle": "chogahui05"
    },
    {
      "name": "남현욱",
      "school": "Team Samoyed",
      "bojHandle": "jwvg0425"
    },
    {
      "name": "권일우",
      "school": "인천대학교",
      "bojHandle": "rdd6584"
    }
  ],
  "sponsor": [
    {
      "id": "kakao",
      "name": "카카오"
    },
    {
      "id": "naver-d2",
      "name": "NAVER D2"
    },
    {
      "id": "mnsoft",
      "name": "현대엠엔소프트"
    },
    {
      "id": "jetbrains",
      "name": "JetBrains"
    },
    {
      "id": "hanbit",
      "name": "한빛미디어"
    },
    {
      "id": "jpub",
      "name": "제이펍"
    },
    {
      "id": "youngjin",
      "name": "영진닷컴"
    },
    {
      "id": "startlink",
      "name": "스타트링크"
    }
  ]
}

=== icpc-sinchon/icpc-sinchon-workspace/libs/data/suapc/2025-Winter.json
{
  "$schema": "./schema.json",
  "year": 2025,
  "season": "Winter",
  "dateTime": "2025년 2월 22일(토) 오후 12시 ~ 오후 5시",
  "note": "",
  "links": {
    "problemBojLink": "https://www.acmicpc.net/category/detail/4440",
    "problemPdf": "https://drive.google.com/file/d/1qD7tQ7a7fBrocIZg4QF4vgGlO0vxtYAI/view",
    "solutionPdf": "https://upload.acmicpc.net/65dbe77c-88d9-4e81-986d-fb5d36d06a9d/",
    "scoreboard": ["https://www.acmicpc.net/contest/spotboard/1449"],
    "posterImage": "https://drive.google.com/file/d/12XT8tsDv3A5ajGhRPJfzUU1aCTp5ytqu/view"
  },
  "contest": [
    {
      "contestName": null,
      "awards": [
        {
          "rank": 1,
          "solved": 12,
          "teamName": "대충 26년 전역 어쩌고",
          "school": "연세대학교",
          "member": ["이도훈", "이협", "최우현"]
        },
        {
          "rank": 2,
          "solved": 12,
          "teamName": "배신저스",
          "school": "서강대학교",
          "member": ["송근수", "강효규", "채성우"]
        },
        {
          "rank": 3,
          "solved": 11,
          "teamName": "나근육또녹을지도",
          "school": "서강대학교",
          "member": ["김동건", "이승형", "조원빈"]
        },
        {
          "rank": 4,
          "solved": 11,
          "teamName": "black box",
          "school": "연세대학교",
          "member": ["이재열", "윤지호", "김건우"]
        },
        {
          "rank": 5,
          "solved": 11,
          "teamName": "calientacabezas",
          "school": "서강대학교, 연세대학교",
          "member": ["최환", "정재헌", "박동언"]
        },
        {
          "rank": 6,
          "solved": 11,
          "teamName": "공면공",
          "school": "연세대학교, 숙명여자대학교, 서강대학교",
          "member": ["박경욱", "길수민", "박준영"]
        },
        {
          "rank": 7,
          "solved": 9,
          "teamName": "wowSpirit",
          "school": "홍익대학교",
          "member": ["송한서", "이가은", "한승준"]
        },
        {
          "rank": 8,
          "solved": 9,
          "teamName": "chill솔 못 했지만 chill하게 한 잔 하는 chill guy들",
          "school": "서강대학교",
          "member": ["김진수", "조성훈", "하건영"]
        },
        {
          "rank": 9,
          "solved": 8,
          "teamName": "우리팀명 뭐로할래",
          "school": "서강대학교",
          "member": ["김규민", "양제웅", "이승찬"]
        },
        {
          "rank": 10,
          "solved": 8,
          "teamName": "김재현",
          "school": "홍익대학교",
          "member": ["정재현", "김도현", "김재헌"]
        }
      ],
      "problemList": [
        {
          "problemTitle": "노트북 세 대를 가지고 왔다",
          "link": "https://www.acmicpc.net/problem/33515",
          "setter": {
            "name": "김형진",
            "school": "연세대학교",
            "bojHandle": "plast"
          }
        },
        {
          "problemTitle": "skeep 문자열",
          "link": "https://www.acmicpc.net/problem/33516",
          "setter": {
            "name": "박주형",
            "school": "경북대학교",
            "bojHandle": "we12223"
          }
        },
        {
          "problemTitle": "징검다리 게임",
          "link": "https://www.acmicpc.net/problem/33517",
          "setter": {
            "name": "유상혁",
            "school": "비공개",
            "bojHandle": "golazcc83"
          }
        },
        {
          "problemTitle": "도로 공사",
          "link": "https://www.acmicpc.net/problem/33518",
          "setter": {
            "name": "허준영",
            "school": "비공개",
            "bojHandle": "jyheo98"
          }
        },
        {
          "problemTitle": "Andrew the Diver",
          "link": "https://www.acmicpc.net/problem/33519",
          "setter": {
            "name": "이현빈",
            "school": "한양대학교",
            "bojHandle": "my3"
          }
        },
        {
          "problemTitle": "초코바 만들기",
          "link": "https://www.acmicpc.net/problem/33520",
          "setter": {
            "name": "김형진",
            "school": "연세대학교",
            "bojHandle": "plast"
          }
        },
        {
          "problemTitle": "장비 강화하기",
          "link": "https://www.acmicpc.net/problem/33521",
          "setter": {
            "name": "유상혁",
            "school": "비공개",
            "bojHandle": "golazcc83"
          }
        },
        {
          "problemTitle": "완전 그래프와 쿼리",
          "link": "https://www.acmicpc.net/problem/33522",
          "setter": {
            "name": "박**",
            "school": "비공개",
            "bojHandle": "isekaijoucho"
          }
        },
        {
          "problemTitle": "체리 컴퍼니",
          "link": "https://www.acmicpc.net/problem/33523",
          "setter": {
            "name": "박진한",
            "school": "고려대학교",
            "bojHandle": "jinhan814"
          }
        },
        {
          "problemTitle": "blobnom.xyz",
          "link": "https://www.acmicpc.net/problem/33524",
          "setter": {
            "name": "장래오",
            "school": "포항공과대학교",
            "bojHandle": "leo020630"
          }
        },
        {
          "problemTitle": "학식 뭐 먹지",
          "link": "https://www.acmicpc.net/problem/33525",
          "setter": {
            "name": "김영인",
            "school": "국민대학교",
            "bojHandle": "young_out"
          }
        },
        {
          "problemTitle": "Anti-Fan Death",
          "link": "https://www.acmicpc.net/problem/33526",
          "setter": {
            "name": "정치훈",
            "school": "비공개",
            "bojHandle": "wjdclgns12"
          }
        },
        {
          "problemTitle": "신촌 길찾기 서비스",
          "link": "https://www.acmicpc.net/problem/33527",
          "setter": {
            "name": "유상혁",
            "school": "비공개",
            "bojHandle": "golazcc83"
          }
        }
      ]
    }
  ],
  "setter": [
    {
      "name": "김형진",
      "school": "연세대학교",
      "bojHandle": "plast"
    },
    {
      "name": "박주형",
      "school": "경북대학교",
      "bojHandle": "we12223"
    },
    {
      "name": "유상혁",
      "school": "비공개",
      "bojHandle": "golazcc83"
    },
    {
      "name": "허준영",
      "school": "비공개",
      "bojHandle": "jyheo98"
    },
    {
      "name": "이현빈",
      "school": "한양대학교",
      "bojHandle": "my3"
    },
    {
      "name": "박**",
      "school": "비공개",
      "bojHandle": "isekaijoucho"
    },
    {
      "name": "박진한",
      "school": "고려대학교",
      "bojHandle": "jinhan814"
    },
    {
      "name": "장래오",
      "school": "포항공과대학교",
      "bojHandle": "leo020630"
    },
    {
      "name": "김영인",
      "school": "국민대학교",
      "bojHandle": "young_out"
    },
    {
      "name": "정치훈",
      "school": "비공개",
      "bojHandle": "wjdclgns12"
    }
  ],
  "reviewer": [
    {
      "name": "김민상",
      "school": "숭실대학교",
      "bojHandle": "tony9402"
    },
    {
      "name": "주감동",
      "school": "국민대학교",
      "bojHandle": "jthis"
    },
    {
      "name": "김재우",
      "school": "고려대학교",
      "bojHandle": "eoaud0108"
    },
    {
      "name": "김동우",
      "school": "고려대학교",
      "bojHandle": "kidw0124"
    },
    {
      "name": "이국렬",
      "school": "연세대학교, Samsung Research",
      "bojHandle": "lky7674"
    }
  ],
  "sponsor": [
    {
      "id": "autoever",
      "name": "현대오토에버"
    },
    {
      "id": "startlink",
      "name": "스타트링크"
    },
    {
      "id": "cubrid",
      "name": "큐브리드"
    },
    {
      "id": "inflearn",
      "name": "인프런"
    },
    {
      "id": "recommend",
      "name": "리코멘드"
    },
    {
      "id": "jpub",
      "name": "제이펍"
    },
    {
      "id": "easyspub",
      "name": "이지스퍼블리싱"
    },
    {
      "id": "insight",
      "name": "인사이트"
    }
  ],
  "personalSponsor": [
    {
      "id": "서희",
      "name": "서희"
    },
    {
      "id": "pjshwa",
      "name": "pjshwa"
    },
    {
      "id": "김규진",
      "name": "김규진"
    },
    {
      "id": "utilForever",
      "name": "utilForever"
    },
    {
      "id": "lky7674(이국렬)",
      "name": "lky7674(이국렬)"
    },
    {
      "id": "이재열",
      "name": "이재열"
    }
  ]
}
