=== icpc-sinchon/icpc-sinchon-workspace/libs/data/suapc/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "title": "SUAPC",
  "description": "신촌지역 대학교 프로그래밍 동아리 연합대회 기록을 담은 데이터 스키마",
  "definitions": {
    "person": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "이름"
        },
        "school": {
          "type": "string",
          "description": "소속 학교"
        },
        "bojHandle": {
          "type": "string",
          "description": "BOJ 아이디"
        }
      },
      "required": ["name", "school", "bojHandle"]
    },
    "sponsor": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "후원사 ID"
        },
        "name": {
          "type": "string",
          "description": "후원 이름"
        },
        "note": {
          "type": "array",
          "description": "후원 관련 기록",
          "items": {
            "type": "string"
          }
        }
      },
      "required": ["id", "name"]
    }
  },
  "properties": {
    "year": {
      "type": "integer",
      "description": "연합 대회가 진행된 연도",
      "minimum": 2019
    },
    "season": {
      "type": "string",
      "description": "연합 대회가 진행된 계절(여름, 겨울 중 하나)",
      "enum": ["Winter", "Summer"]
    },
    "dateTime": {
      "type": "string",
      "description": "연합 대회가 진행된 날짜와 시간"
    },
    "note": {
      "type": "string",
      "description": "대회에 관련된 사항. 이때 특별했던 시기적 이슈 등을 기록"
    },
    "links": {
      "type": "object",
      "description": "연합 대회 관련 링크",
      "properties": {
        "problemBojLink": {
          "type": "string",
          "description": "캠프 콘테스트의 문제 BOJ 링크"
        },
        "problemPdf": {
          "type": "string",
          "description": "캠프 콘테스트의 문제 PDF 링크"
        },
        "solutionPdf": {
          "type": "string",
          "description": "캠프 콘테스트의 솔루션 PDF 링크"
        },
        "scoreboard": {
          "type": "array",
          "description": "캠프 콘테스트의 스코어보드 링크들. div1, div2가 있던 시절을 대비해 배열로 처리",
          "items": {
            "type": "string",
            "description": "캠프 콘테스트의 스코어보드 링크"
          },
          "minItems": 1,
          "maxItems": 3
        },
        "posterImage": {
          "type": "string",
          "description": "연합 대회의 공식 포스터 이미지 링크"
        }
      }
    },
    "contest": {
      "type": "array",
      "description": "SUAPC 대회 목록",
      "items": {
        "$ref": "./contest.json#/definitions/contest"
      }
    },
    "setter": {
      "type": "array",
      "description": "SUAPC 문제 출제자",
      "items": {
        "$ref": "#/definitions/person"
      }
    },
    "reviewer": {
      "type": "array",
      "description": "SUAPC 문제 검수자",
      "items": {
        "$ref": "#/definitions/person"
      }
    },
    "sponsor": {
      "type": "array",
      "description": "SUAPC 후원사",
      "items": {
        "$ref": "#/definitions/sponsor"
      }
    },
    "personalSponsor": {
      "type": "array",
      "description": "SUAPC의 개인 후원자",
      "items": {
        "$ref": "#/definitions/sponsor"
      }
    }
  },
  "required": [
    "year",
    "season",
    "dateTime",
    "links",
    "contest",
    "setter",
    "reviewer",
    "sponsor"
  ]
}

=== icpc-sinchon/icpc-sinchon-workspace/libs/data/suapc/2022-Winter.json
{
  "$schema": "./schema.json",
  "year": 2022,
  "season": "Winter",
  "dateTime": "2022년 2월 26일(토) 오후 12시 ~ 오후 5시",
  "note": "",
  "links": {
    "problemBojLink": "https://www.acmicpc.net/category/detail/3032",
    "problemPdf": "SUAPC_2022w_Problem.pdf",
    "solutionPdf": "SUAPC_2022w_Solution.pdf",
    "scoreboard": ["https://www.acmicpc.net/contest/spotboard/764"],
    "posterImage": "SUAPC_2022w_Poster.jpg"
  },
  "contest": [
    {
      "contestName": null,
      "awards": [
        {
          "rank": 1,
          "solved": 7,
          "teamName": "5시간 집중하기 힘든 나이",
          "school": "서강대학교",
          "member": ["박재형", "오재석", "진상우"]
        },
        {
          "rank": 2,
          "solved": 7,
          "teamName": "서강베스트",
          "school": "서강대학교",
          "member": ["김동건", "이재혁", "조원빈"]
        },
        {
          "rank": 3,
          "solved": 7,
          "teamName": "정열맨",
          "school": "홍익대학교",
          "member": ["김도현", "김재헌", "정재현"]
        },
        {
          "rank": 4,
          "solved": 7,
          "teamName": "No Seastar Can't Win",
          "school": "서강대학교",
          "member": ["김정모", "김준우", "박준서"]
        },
        {
          "rank": 5,
          "solved": 7,
          "teamName": "ECM",
          "school": "서강대학교",
          "member": ["권지은", "김성현", "김창민"]
        },
        {
          "rank": 6,
          "solved": 7,
          "teamName": "BIROSO",
          "school": "서강대학교",
          "member": ["김예진", "김용현", "박민성"]
        },
        {
          "rank": 7,
          "solved": 7,
          "teamName": "어라랍스타",
          "school": "연세대학교",
          "member": ["김종민", "김태윤", "이승재"]
        },
        {
          "rank": 8,
          "solved": 7,
          "teamName": "하와이안 민트초코",
          "school": "연세대학교",
          "member": ["김건우", "유영서", "전재현"]
        },
        {
          "rank": 9,
          "solved": 7,
          "teamName": "so강은 so 강하다",
          "school": "서강대학교",
          "member": ["강효규", "김서인", "신동준"]
        },
        {
          "rank": 10,
          "solved": 7,
          "teamName": "홍입2출할리스20시알바따뜻한아아할줄알아요",
          "school": "연세대학교",
          "member": ["곽재혁", "이훈재", "임승원"]
        }
      ],
      "problemList": [
        {
          "problemTitle": "튜터-튜티 관계의 수",
          "link": "https://www.acmicpc.net/problem/24542",
          "setter": {
            "name": "박찬솔",
            "school": "숭실대학교",
            "bojHandle": "chansol"
          }
        },
        {
          "problemTitle": "선인장이 무럭무럭 자라고 있어요",
          "link": "https://www.acmicpc.net/problem/24543",
          "setter": {
            "name": "이국렬",
            "school": "연세대학교",
            "bojHandle": "lky7674"
          }
        },
        {
          "problemTitle": "카카오뷰 큐레이팅 효용성 분석",
          "link": "https://www.acmicpc.net/problem/24544",
          "setter": {
            "name": "홍은기",
            "school": "삼성전자",
            "bojHandle": "pichulia"
          }
        },
        {
          "problemTitle": "Y",
          "link": "https://www.acmicpc.net/problem/24545",
          "setter": {
            "name": "조찬우",
            "school": "선린인터넷고등학교",
            "bojHandle": "myyh1234"
          }
        },
        {
          "problemTitle": "놀이기구에 진심인 편",
          "link": "https://www.acmicpc.net/problem/24546",
          "setter": {
            "name": "이상원",
            "school": "삼성전자",
            "bojHandle": "gumgood"
          }
        },
        {
          "problemTitle": "mod와 쿼리",
          "link": "https://www.acmicpc.net/problem/24547",
          "setter": {
            "name": "김태영",
            "school": "KAIST",
            "bojHandle": "tae826"
          }
        },
        {
          "problemTitle": "도로 정보",
          "link": "https://www.acmicpc.net/problem/24548",
          "setter": {
            "name": "박진식",
            "school": "크리마",
            "bojHandle": "pjshwa"
          }
        },
        {
          "problemTitle": "신촌방위본부의 부대 배치",
          "link": "https://www.acmicpc.net/problem/24549",
          "setter": {
            "name": "이국렬",
            "school": "연세대학교",
            "bojHandle": "lky7674"
          }
        },
        {
          "problemTitle": "이 멋진 수열에 쿼리를!",
          "link": "https://www.acmicpc.net/problem/24550",
          "setter": {
            "name": "홍은기",
            "school": "삼성전자",
            "bojHandle": "pichulia"
          }
        },
        {
          "problemTitle": "일이 너무 많아...",
          "link": "https://www.acmicpc.net/problem/24551",
          "setter": {
            "name": "홍은기",
            "school": "삼성전자",
            "bojHandle": "pichulia"
          }
        },
        {
          "problemTitle": "올바른 괄호",
          "link": "https://www.acmicpc.net/problem/24552",
          "setter": {
            "name": "박찬솔",
            "school": "숭실대학교",
            "bojHandle": "chansol"
          }
        },
        {
          "problemTitle": "팰린드롬 게임",
          "link": "https://www.acmicpc.net/problem/24553",
          "setter": {
            "name": "김태영",
            "school": "KAIST",
            "bojHandle": "tae826"
          }
        },
        {
          "problemTitle": "불협화음",
          "link": "https://www.acmicpc.net/problem/24554",
          "setter": {
            "name": "홍은기",
            "school": "삼성전자",
            "bojHandle": "pichulia"
          }
        }
      ]
    }
  ],
  "setter": [
    {
      "name": "김태영",
      "school": "KAIST",
      "bojHandle": "tae826"
    },
    {
      "name": "박진식",
      "school": "크리마",
      "bojHandle": "pjshwa"
    },
    {
      "name": "박찬솔",
      "school": "숭실대학교",
      "bojHandle": "chansol"
    },
    {
      "name": "이국렬",
      "school": "연세대학교",
      "bojHandle": "lky7674"
    },
    {
      "name": "이상원",
      "school": "삼성전자",
      "bojHandle": "gumgood"
    },
    {
      "name": "조찬우",
      "school": "선린인터넷고등학교",
      "bojHandle": "myyh1234"
    },
    {
      "name": "홍은기",
      "school": "삼성전자",
      "bojHandle": "pichulia"
    }
  ],
  "reviewer": [
    {
      "name": "김동규",
      "school": "KAIST AI대학원",
      "bojHandle": "eaststar"
    },
    {
      "name": "강희원",
      "school": "경기북과학고등학교",
      "bojHandle": "heeda0528"
    },
    {
      "name": "남현욱",
      "school": "Team Samoyed",
      "bojHandle": "jwvg0425"
    },
    {
      "name": "서태수",
      "school": "삼성전자",
      "bojHandle": "cheetose"
    },
    {
      "name": "최재민",
      "school": "KAIST",
      "bojHandle": "jh05013"
    }
  ],
  "sponsor": [
    {
      "id": "kakao",
      "name": "카카오"
    },
    {
      "id": "autoever",
      "name": "현대오토에버"
    },
    {
      "id": "hello-algo",
      "name": "헬로알고"
    },
    {
      "id": "naver-d2",
      "name": "네이버 D2"
    },
    {
      "id": "secmem",
      "name": "삼성소프트웨어멤버십"
    },
    {
      "id": "jetbrains",
      "name": "JetBrains"
    },
    {
      "id": "youngjin",
      "name": "영진닷컴"
    },
    {
      "id": "easyspub",
      "name": "이지스퍼블리싱"
    },
    {
      "id": "hanbit",
      "name": "한빛미디어"
    },
    {
      "id": "startlink",
      "name": "스타트링크"
    }
  ]
}

=== icpc-sinchon/icpc-sinchon-workspace/libs/data/suapc/2023-Summer.json
{
  "$schema": "./schema.json",
  "year": 2023,
  "season": "Summer",
  "dateTime": "2023년 8월 26일(토) 오후 12시 ~ 오후 5시",
  "note": "",
  "links": {
    "problemBojLink": "https://www.acmicpc.net/category/detail/3855",
    "solutionPdf": "SUAPC_2023_Summer_Solution.pdf",
    "scoreboard": ["https://www.acmicpc.net/contest/spotboard/1104"],
    "posterImage": "SUAPC_2023s_Poster.jpeg"
  },
  "contest": [
    {
      "contestName": null,
      "awards": [
        {
          "rank": 1,
          "solved": 12,
          "teamName": "Redshift",
          "school": "서강대학교",
          "member": ["박수현", "이준석", "채성우"]
        },
        {
          "rank": 2,
          "solved": 11,
          "teamName": "SCC_Sinchon Coding Champions",
          "school": "연세대학교",
          "member": ["김태윤", "정용진", "김건우"]
        },
        {
          "rank": 3,
          "solved": 11,
          "teamName": "월파출신 코치가 가르치고 있어요",
          "school": "서강대학교",
          "member": ["송근수", "이승형", "박성준"]
        },
        {
          "rank": 4,
          "solved": 10,
          "teamName": "가오당",
          "school": "연세대학교",
          "member": ["한의엽", "전우제", "이지언"]
        },
        {
          "rank": 5,
          "solved": 9,
          "teamName": "1등하러왔습니다",
          "school": "연세대학교",
          "member": ["곽재혁", "김형진", "박경욱"]
        },
        {
          "rank": 6,
          "solved": 9,
          "teamName": "병공병",
          "school": "홍익대학교",
          "member": ["정재현", "김도현", "김재헌"]
        },
        {
          "rank": 7,
          "solved": 9,
          "teamName": "조성훈",
          "school": "서강대학교",
          "member": ["조성훈", "조원빈", "김동건"]
        },
        {
          "rank": 8,
          "solved": 8,
          "teamName": "기령손의 그녀들",
          "school": "서강대학교",
          "member": ["강효규", "김서인", "장유빈"]
        },
        {
          "rank": 9,
          "solved": 7,
          "teamName": "WooJeans",
          "school": "서강대학교",
          "member": ["이우진", "정회윤", "유호영"]
        },
        {
          "rank": 10,
          "solved": 6,
          "teamName": "홍하예프",
          "school": "홍익대학교",
          "member": ["한승준", "전승민", "심동현"]
        }
      ],
      "problemList": [
        {
          "problemTitle": "A→B",
          "link": "https://www.acmicpc.net/problem/29149",
          "setter": {
            "name": "이도훈",
            "school": "연세대학교",
            "bojHandle": "dhlee1031"
          }
        },
        {
          "problemTitle": "기초적인 문제",
          "link": "https://www.acmicpc.net/problem/29150",
          "setter": {
            "name": "이명헌",
            "school": "연세대학교",
            "bojHandle": "nflight11"
          }
        },
        {
          "problemTitle": "2048",
          "link": "https://www.acmicpc.net/problem/29151",
          "setter": {
            "name": "최우현",
            "school": "연세대학교",
            "bojHandle": "starwh03"
          }
        },
        {
          "problemTitle": "디지털 트윈",
          "link": "https://www.acmicpc.net/problem/29152",
          "setter": {
            "name": "이협",
            "school": "연세대학교",
            "bojHandle": "dlguq0107"
          }
        },
        {
          "problemTitle": "성게밭",
          "link": "https://www.acmicpc.net/problem/29153",
          "setter": {
            "name": "이협",
            "school": "연세대학교",
            "bojHandle": "dlguq0107"
          }
        },
        {
          "problemTitle": "작곡가 A의 시창 평가",
          "link": "https://www.acmicpc.net/problem/29154",
          "setter": {
            "name": "길수민",
            "school": "숙명여자대학교",
            "bojHandle": "2093ab"
          }
        },
        {
          "problemTitle": "개발자 지망생 구름이의 취업 뽀개기",
          "link": "https://www.acmicpc.net/problem/29155",
          "setter": {
            "name": "길수민",
            "school": "숙명여자대학교",
            "bojHandle": "2093ab"
          }
        },
        {
          "problemTitle": "탭 UI",
          "link": "https://www.acmicpc.net/problem/29156",
          "setter": {
            "name": "신정환",
            "school": "성균관대학교",
            "bojHandle": "shjohw12"
          }
        },
        {
          "problemTitle": "폭탄 피하기",
          "link": "https://www.acmicpc.net/problem/29157",
          "setter": {
            "name": "이지훈",
            "school": "서강대학교",
            "bojHandle": "maker29"
          }
        },
        {
          "problemTitle": "큰 수 만들기 게임",
          "link": "https://www.acmicpc.net/problem/29158",
          "setter": {
            "name": "이지훈",
            "school": "서강대학교",
            "bojHandle": "maker29"
          }
        },
        {
          "problemTitle": "케이크 두 개",
          "link": "https://www.acmicpc.net/problem/29159",
          "setter": {
            "name": "이명헌",
            "school": "연세대학교",
            "bojHandle": "nflight11"
          }
        },
        {
          "problemTitle": "나의 FIFA 팀 가치는?",
          "link": "https://www.acmicpc.net/problem/29160",
          "setter": {
            "name": "이지훈",
            "school": "서강대학교",
            "bojHandle": "maker29"
          }
        },
        {
          "problemTitle": "트리와 케이",
          "link": "https://www.acmicpc.net/problem/29161",
          "setter": {
            "name": "최우현",
            "school": "연세대학교",
            "bojHandle": "starwh03"
          }
        },
        {
          "problemTitle": "북극여우는 괄호를 뒤집어",
          "link": "https://www.acmicpc.net/problem/29162",
          "setter": {
            "name": "이협",
            "school": "연세대학교",
            "bojHandle": "dlguq0107"
          }
        }
      ]
    }
  ],
  "setter": [
    {
      "name": "길수민",
      "school": "숙명여자대학교",
      "bojHandle": "2093ab"
    },
    {
      "name": "신정환",
      "school": "성균관대학교",
      "bojHandle": "shjohw12"
    },
    {
      "name": "이도훈",
      "school": "연세대학교",
      "bojHandle": "dhlee1031"
    },
    {
      "name": "이명헌",
      "school": "연세대학교",
      "bojHandle": "nflight11"
    },
    {
      "name": "이지훈",
      "school": "서강대학교",
      "bojHandle": "maker29"
    },
    {
      "name": "이협",
      "school": "연세대학교",
      "bojHandle": "dlguq0107"
    },
    {
      "name": "최우현",
      "school": "연세대학교",
      "bojHandle": "starwh03"
    }
  ],
  "reviewer": [
    {
      "name": "김영현",
      "school": "서울대학교",
      "bojHandle": "kipa00"
    },
    {
      "name": "박찬솔",
      "school": "숭실대학교",
      "bojHandle": "chansol"
    },
    {
      "name": "심유근",
      "school": "서울대학교",
      "bojHandle": "cozyyg"
    },
    {
      "name": "이국렬",
      "school": "연세대학교",
      "bojHandle": "lky7674"
    },
    {
      "name": "cologne",
      "school": "(비공개)",
      "bojHandle": "cologne"
    }
  ],
  "sponsor": [
    {
      "id": "autoever",
      "name": "현대오토에버"
    },
    {
      "id": "nexon",
      "name": "넥슨"
    },
    {
      "id": "hanbit",
      "name": "한빛미디어"
    },
    {
      "id": "easyspub",
      "name": "이지스퍼블리싱"
    },
    {
      "id": "goorm",
      "name": "구름"
    },
    {
      "id": "startlink",
      "name": "스타트링크"
    },
    {
      "id": "moloco",
      "name": "몰로코"
    },
    {
      "id": "jpub",
      "name": "제이펍"
    },
    {
      "id": "solvedac",
      "name": "솔브드"
    }
  ]
}

=== icpc-sinchon/icpc-sinchon-workspace/libs/data/suapc/2022-Summer.json
{
  "$schema": "./schema.json",
  "year": 2022,
  "season": "Summer",
  "dateTime": "2022년 9월 4일(일) 오후 12시 ~ 오후 5시",
  "note": "",
  "links": {
    "problemBojLink": "https://www.acmicpc.net/category/detail/3180",
    "problemPdf": "SUAPC_2022_Summer_Problems.pdf",
    "solutionPdf": "SUAPC_2022_Summer_Solutions.pdf",
    "scoreboard": ["https://www.acmicpc.net/contest/spotboard/840"],
    "posterImage": "SUAPC_2022s_Poster.jpg"
  },
  "contest": [
    {
      "contestName": null,
      "awards": [
        {
          "rank": 1,
          "solved": 11,
          "teamName": "우승하러 왔습니다",
          "school": "서강대학교",
          "member": ["강효규", "박재형", "채성우"]
        },
        {
          "rank": 2,
          "solved": 10,
          "teamName": "DSP",
          "school": "서강대학교",
          "member": ["김동건", "이준석", "전민수"]
        },
        {
          "rank": 3,
          "solved": 10,
          "teamName": "백준검색창에lky7674를검색해보세요",
          "school": "연세대학교",
          "member": ["김건우", "김종민", "정기웅"]
        },
        {
          "rank": 4,
          "solved": 9,
          "teamName": "정열맨",
          "school": "홍익대학교",
          "member": ["김도현", "김재헌", "정재현"]
        },
        {
          "rank": 5,
          "solved": 9,
          "teamName": "삼대진미",
          "school": "연세대학교",
          "member": ["김태윤", "이협", "최우현"]
        },
        {
          "rank": 6,
          "solved": 8,
          "teamName": "djs212222",
          "school": "서강대학교",
          "member": ["김서인", "김정모", "이재혁"]
        },
        {
          "rank": 7,
          "solved": 7,
          "teamName": "ㅡㅡㅡㅡㅡ수상컷ㅡㅡㅡㅡㅡ",
          "school": "서강대학교",
          "member": ["성주희", "조성훈", "정회윤"]
        },
        {
          "rank": 8,
          "solved": 6,
          "teamName": "신촌 노랑통닭",
          "school": "연세대학교",
          "member": ["김민수", "곽재혁", "노준영"]
        },
        {
          "rank": 9,
          "solved": 6,
          "teamName": "전역 3일 전 SUAPC 하는 중",
          "school": "연세대학교",
          "member": ["박광호", "조우현", "한의엽"]
        },
        {
          "rank": 10,
          "solved": 6,
          "teamName": "종환지훈준석",
          "school": "서강대학교",
          "member": ["이지훈", "이준석", "임종환"]
        }
      ],
      "problemList": [
        {
          "problemTitle": "수 맞히기 게임",
          "link": "https://www.acmicpc.net/problem/25557",
          "setter": {
            "name": "신용명",
            "school": "한양대학교",
            "bojHandle": "tlsdydaud1"
          }
        },
        {
          "problemTitle": "내비게이션",
          "link": "https://www.acmicpc.net/problem/25558",
          "setter": {
            "name": "이국렬",
            "school": "연세대학교",
            "bojHandle": "lky7674"
          }
        },
        {
          "problemTitle": "패스",
          "link": "https://www.acmicpc.net/problem/25559",
          "setter": {
            "name": "신용명",
            "school": "한양대학교",
            "bojHandle": "tlsdydaud1"
          }
        },
        {
          "problemTitle": "포탈",
          "link": "https://www.acmicpc.net/problem/25560",
          "setter": {
            "name": "신용명",
            "school": "한양대학교",
            "bojHandle": "tlsdydaud1"
          }
        },
        {
          "problemTitle": "1-3 트리",
          "link": "https://www.acmicpc.net/problem/25561",
          "setter": {
            "name": "신용명",
            "school": "한양대학교",
            "bojHandle": "tlsdydaud1"
          }
        },
        {
          "problemTitle": "차의 개수",
          "link": "https://www.acmicpc.net/problem/25562",
          "setter": {
            "name": "강희원",
            "school": "경기과학고등학교",
            "bojHandle": "heeda0528"
          }
        },
        {
          "problemTitle": "AND, OR, XOR",
          "link": "https://www.acmicpc.net/problem/25563",
          "setter": {
            "name": "장래오",
            "school": "포항공과대학교",
            "bojHandle": "leo020630"
          }
        },
        {
          "problemTitle": "역삼역",
          "link": "https://www.acmicpc.net/problem/25564",
          "setter": {
            "name": "신정환",
            "school": "성균관대학교",
            "bojHandle": "shjohw12"
          }
        },
        {
          "problemTitle": "딸기와 토마토",
          "link": "https://www.acmicpc.net/problem/25565",
          "setter": {
            "name": "강희원",
            "school": "경기과학고등학교",
            "bojHandle": "heeda0528"
          }
        },
        {
          "problemTitle": "김밥",
          "link": "https://www.acmicpc.net/problem/25566",
          "setter": {
            "name": "신정환",
            "school": "성균관대학교",
            "bojHandle": "shjohw12"
          }
        },
        {
          "problemTitle": "줄 세우기",
          "link": "https://www.acmicpc.net/problem/25567",
          "setter": {
            "name": "박찬솔",
            "school": "숭실대학교",
            "bojHandle": "chansol"
          }
        },
        {
          "problemTitle": "피라미드",
          "link": "https://www.acmicpc.net/problem/25568",
          "setter": {
            "name": "박진식",
            "school": "크리마",
            "bojHandle": "pjshwa"
          }
        },
        {
          "problemTitle": "My뷰 꾸미기",
          "link": "https://www.acmicpc.net/problem/25569",
          "setter": {
            "name": "박진식",
            "school": "크리마",
            "bojHandle": "pjshwa"
          }
        }
      ]
    }
  ],
  "setter": [
    {
      "name": "강희원",
      "school": "경기과학고등학교",
      "bojHandle": "heeda0528"
    },
    {
      "name": "박진식",
      "school": "크리마",
      "bojHandle": "pjshwa"
    },
    {
      "name": "박찬솔",
      "school": "숭실대학교",
      "bojHandle": "chansol"
    },
    {
      "name": "신용명",
      "school": "한양대학교",
      "bojHandle": "tlsdydaud1"
    },
    {
      "name": "신정환",
      "school": "성균관대학교",
      "bojHandle": "shjohw12"
    },
    {
      "name": "이국렬",
      "school": "연세대학교",
      "bojHandle": "lky7674"
    },
    {
      "name": "장래오",
      "school": "포항공과대학교",
      "bojHandle": "leo020630"
    }
  ],
  "reviewer": [
    {
      "name": "김동규",
      "school": "KAIST AI대학원",
      "bojHandle": "eaststar"
    },
    {
      "name": "김태영",
      "school": "KAIST",
      "bojHandle": "tae826"
    },
    {
      "name": "남현욱",
      "school": "팀 사모예드",
      "bojHandle": "jwvg0425"
    },
    {
      "name": "문정후",
      "school": "경기과학고등학교",
      "bojHandle": "mjhmjh1104"
    },
    {
      "name": "이상원",
      "school": "삼성전자",
      "bojHandle": "gumgood"
    }
  ],
  "sponsor": [
    {
      "id": "kakao",
      "name": "카카오"
    },
    {
      "id": "autoever",
      "name": "현대오토에버"
    },
    {
      "id": "naver-d2",
      "name": "NAVER D2"
    },
    {
      "id": "secmem",
      "name": "삼성소프트웨어멤버십"
    },
    {
      "id": "youngjin",
      "name": "영진닷컴"
    },
    {
      "id": "easyspub",
      "name": "이지스퍼블리싱"
    },
    {
      "id": "hanbit",
      "name": "한빛미디어"
    },
    {
      "id": "jetbrains",
      "name": "JetBrains"
    },
    {
      "id": "planetarium",
      "name": "플라네타리움"
    },
    {
      "id": "moloco",
      "name": "Moloco"
    },
    {
      "id": "devocean",
      "name": "데보션"
    },
    {
      "id": "jpub",
      "name": "제이펍"
    },
    {
      "id": "startlink",
      "name": "스타트링크"
    }
  ]
}
