=== icpc-sinchon/icpc-sinchon-workspace/libs/data/suapc/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "title": "SUAPC",
  "description": "신촌지역 대학교 프로그래밍 동아리 연합대회 기록을 담은 데이터 스키마",
  "definitions": {
    "person": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "이름"
        },
        "school": {
          "type": "string",
          "description": "소속 학교"
        },
        "bojHandle": {
          "type": "string",
          "description": "BOJ 아이디"
        }
      },
      "required": ["name", "school", "bojHandle"]
    },
    "sponsor": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "후원사 ID"
        },
        "name": {
          "type": "string",
          "description": "후원 이름"
        },
        "note": {
          "type": "array",
          "description": "후원 관련 기록",
          "items": {
            "type": "string"
          }
        }
      },
      "required": ["id", "name"]
    }
  },
  "properties": {
    "year": {
      "type": "integer",
      "description": "연합 대회가 진행된 연도",
      "minimum": 2019
    },
    "season": {
      "type": "string",
      "description": "연합 대회가 진행된 계절(여름, 겨울 중 하나)",
      "enum": ["Winter", "Summer"]
    },
    "dateTime": {
      "type": "string",
      "description": "연합 대회가 진행된 날짜와 시간"
    },
    "note": {
      "type": "string",
      "description": "대회에 관련된 사항. 이때 특별했던 시기적 이슈 등을 기록"
    },
    "links": {
      "type": "object",
      "description": "연합 대회 관련 링크",
      "properties": {
        "problemBojLink": {
          "type": "string",
          "description": "캠프 콘테스트의 문제 BOJ 링크"
        },
        "problemPdf": {
          "type": "string",
          "description": "캠프 콘테스트의 문제 PDF 링크"
        },
        "solutionPdf": {
          "type": "string",
          "description": "캠프 콘테스트의 솔루션 PDF 링크"
        },
        "scoreboard": {
          "type": "array",
          "description": "캠프 콘테스트의 스코어보드 링크들. div1, div2가 있던 시절을 대비해 배열로 처리",
          "items": {
            "type": "string",
            "description": "캠프 콘테스트의 스코어보드 링크"
          },
          "minItems": 1,
          "maxItems": 3
        },
        "posterImage": {
          "type": "string",
          "description": "연합 대회의 공식 포스터 이미지 링크"
        }
      }
    },
    "contest": {
      "type": "array",
      "description": "SUAPC 대회 목록",
      "items": {
        "$ref": "./contest.json#/definitions/contest"
      }
    },
    "setter": {
      "type": "array",
      "description": "SUAPC 문제 출제자",
      "items": {
        "$ref": "#/definitions/person"
      }
    },
    "reviewer": {
      "type": "array",
      "description": "SUAPC 문제 검수자",
      "items": {
        "$ref": "#/definitions/person"
      }
    },
    "sponsor": {
      "type": "array",
      "description": "SUAPC 후원사",
      "items": {
        "$ref": "#/definitions/sponsor"
      }
    },
    "personalSponsor": {
      "type": "array",
      "description": "SUAPC의 개인 후원자",
      "items": {
        "$ref": "#/definitions/sponsor"
      }
    }
  },
  "required": [
    "year",
    "season",
    "dateTime",
    "links",
    "contest",
    "setter",
    "reviewer",
    "sponsor"
  ]
}

=== icpc-sinchon/icpc-sinchon-workspace/libs/data/suapc/2024-Summer.json
{
  "$schema": "./schema.json",
  "year": 2024,
  "season": "Summer",
  "dateTime": "2024년 8월 25일(토) 오후 12시 ~ 오후 5시",
  "note": "",
  "links": {
    "problemBojLink": "https://www.acmicpc.net/category/detail/4276",
    "solutionPdf": "https://upload.acmicpc.net/d8445ed9-91a0-4df4-b88a-60898c519005/",
    "scoreboard": ["https://www.acmicpc.net/contest/spotboard/1319"],
    "posterImage": "https://drive.google.com/file/d/15TrDAYAf9_jf2ivglRIDzxN6GOPrItpM/view?usp=drive_link"
  },
  "contest": [
    {
      "contestName": null,
      "awards": [
        {
          "rank": 1,
          "solved": 12,
          "teamName": "PS:Endgame",
          "school": "연세대학교",
          "member": ["정용진", "김형진", "김태윤"]
        },
        {
          "rank": 2,
          "solved": 12,
          "teamName": "Redshift",
          "school": "서강대학교",
          "member": ["박수현", "조원빈", "채성우"]
        },
        {
          "rank": 3,
          "solved": 10,
          "teamName": "탈PS는지능순",
          "school": "연세대학교",
          "member": ["이명헌", "곽재혁", "김민준"]
        },
        {
          "rank": 4,
          "solved": 10,
          "teamName": "3인분같은2인분",
          "school": "연세대학교",
          "member": ["김건우", "김지호", "장현우"]
        },
        {
          "rank": 5,
          "solved": 9,
          "teamName": "ALL_TIME_LEGEND",
          "school": "서강대학교",
          "member": ["이승형", "박성준", "송근수"]
        },
        {
          "rank": 6,
          "solved": 9,
          "teamName": "goraani never stop",
          "school": "서강대학교",
          "member": ["강효규", "김동건", "유호영"]
        },
        {
          "rank": 7,
          "solved": 7,
          "teamName": "김재현",
          "school": "홍익대학교",
          "member": ["정재현", "김도현", "김재헌"]
        },
        {
          "rank": 8,
          "solved": 7,
          "teamName": ".",
          "school": "연세대학교",
          "member": ["이협", "이도훈", "최우현"]
        },
        {
          "rank": 9,
          "solved": 6,
          "teamName": "I2C",
          "school": "서강대학교",
          "member": ["김진수", "박준성", "하건영"]
        },
        {
          "rank": 10,
          "solved": 6,
          "teamName": "팀 이름",
          "school": "서강대학교",
          "member": ["조성훈", "손기령", "정회윤"]
        }
      ],
      "problemList": [
        {
          "problemTitle": "SWAPC",
          "link": "https://www.acmicpc.net/problem/32158",
          "setter": {
            "name": "이지언",
            "school": "연세대학교",
            "bojHandle": "ez_code"
          }
        },
        {
          "problemTitle": "평균 구하기",
          "link": "https://www.acmicpc.net/problem/32159",
          "setter": {
            "name": "박상수",
            "school": "Samsung Research",
            "bojHandle": "cki86201"
          }
        },
        {
          "problemTitle": "숫자 놀이",
          "link": "https://www.acmicpc.net/problem/32160",
          "setter": {
            "name": "곽우석",
            "school": "SK하이닉스",
            "bojHandle": "bubbler"
          }
        },
        {
          "problemTitle": "축지법",
          "link": "https://www.acmicpc.net/problem/32161",
          "setter": {
            "name": "전우제",
            "school": "연세대학교",
            "bojHandle": "kiwiyou"
          }
        },
        {
          "problemTitle": "n, 3n, 5n",
          "link": "https://www.acmicpc.net/problem/32162",
          "setter": {
            "name": "곽우석",
            "school": "SK하이닉스",
            "bojHandle": "bubbler"
          }
        },
        {
          "problemTitle": "사탕 배달",
          "link": "https://www.acmicpc.net/problem/32163",
          "setter": {
            "name": "정치훈",
            "school": "Samsung Research",
            "bojHandle": "wjdclgns12"
          }
        },
        {
          "problemTitle": "지워진 ETT",
          "link": "https://www.acmicpc.net/problem/32164",
          "setter": {
            "name": "김도훈",
            "school": "한양대학교",
            "bojHandle": "dohoon"
          }
        },
        {
          "problemTitle": "잊음을 논함",
          "link": "https://www.acmicpc.net/problem/32165",
          "setter": {
            "name": "노현제",
            "school": "서울과학기술대학교",
            "bojHandle": "hjroh0315"
          }
        },
        {
          "problemTitle": "시험 주행",
          "link": "https://www.acmicpc.net/problem/32166",
          "setter": {
            "name": "김영현",
            "school": "서울대학교",
            "bojHandle": "kipa00"
          }
        },
        {
          "problemTitle": "a11y",
          "link": "https://www.acmicpc.net/problem/32167",
          "setter": {
            "name": "박상수",
            "school": "Samsung Research",
            "bojHandle": "cki86201"
          }
        },
        {
          "problemTitle": "완전 이진 트리와 쿼리",
          "link": "https://www.acmicpc.net/problem/32168",
          "setter": {
            "name": "정치훈",
            "school": "Samsung Research",
            "bojHandle": "wjdclgns12"
          }
        },
        {
          "problemTitle": "허술한 보안 프로그램",
          "link": "https://www.acmicpc.net/problem/32169",
          "setter": {
            "name": "서종환",
            "school": "서울대학교",
            "bojHandle": "mujigae"
          }
        },
        {
          "problemTitle": "나무 키우기",
          "link": "https://www.acmicpc.net/problem/32170",
          "setter": {
            "name": "박상수",
            "school": "Samsung Research",
            "bojHandle": "cki86201"
          }
        }
      ]
    }
  ],
  "setter": [
    {
      "name": "이지언",
      "school": "연세대학교",
      "bojHandle": "ez_code"
    },
    {
      "name": "박상수",
      "school": "Samsung Research",
      "bojHandle": "cki86201"
    },
    {
      "name": "곽우석",
      "school": "SK하이닉스",
      "bojHandle": "bubbler"
    },
    {
      "name": "전우제",
      "school": "연세대학교",
      "bojHandle": "kiwiyou"
    },
    {
      "name": "정치훈",
      "school": "Samsung Research",
      "bojHandle": "wjdclgns12"
    },
    {
      "name": "김도훈",
      "school": "한양대학교",
      "bojHandle": "dohoon"
    },
    {
      "name": "김영현",
      "school": "서울대학교",
      "bojHandle": "kipa00"
    },
    {
      "name": "서종환",
      "school": "서울대학교",
      "bojHandle": "mujigae"
    },
    {
      "name": "노현제",
      "school": "서울과학기술대학교",
      "bojHandle": "hjroh0315"
    }
  ],
  "reviewer": [
    {
      "name": "김동현",
      "school": "Moloco",
      "bojHandle": "kdh9949"
    },
    {
      "name": "임병찬",
      "school": "POSTECH",
      "bojHandle": "hyperbolic"
    },
    {
      "name": "장래오",
      "school": "POSTECH",
      "bojHandle": "leo020630"
    },
    {
      "name": "박종경",
      "school": "서울대학교",
      "bojHandle": "jk410"
    },
    {
      "name": "이국렬",
      "school": "연세대학교",
      "bojHandle": "lky7674"
    }
  ],
  "sponsor": [
    {
      "id": "solvedac",
      "name": "솔브드"
    },
    {
      "id": "startlink",
      "name": "스타트링크"
    },
    {
      "id": "autoever",
      "name": "현대오토에버"
    },
    {
      "id": "cubrid",
      "name": "큐브리드"
    },
    {
      "id": "codeit",
      "name": "코드잇"
    },
    {
      "id": "insight",
      "name": "인사이트"
    },
    {
      "id": "goldenrabbit",
      "name": "골든래빗"
    },
    {
      "id": "jpub",
      "name": "제이펍"
    }
  ],
  "personalSponsor": [
    {
      "id": "cubic",
      "name": "cubic"
    },
    {
      "id": "pjshwa",
      "name": "pjshwa"
    },
    {
      "id": "kokokokojima",
      "name": "kokokokojima"
    },
    {
      "id": "신정화",
      "name": "신정화"
    },
    {
      "id": "이지언",
      "name": "이지언"
    }
  ]
}

=== icpc-sinchon/icpc-sinchon-workspace/libs/data/suapc/2021-Summer.json
{
  "$schema": "./schema.json",
  "year": 2021,
  "season": "Summer",
  "dateTime": "2021년 8월 28일 오후 12시 ~ 오후 5시",
  "note": "",
  "links": {
    "problemBojLink": "https://www.acmicpc.net/category/detail/2757",
    "problemPdf": "SUAPC_2021s_Problem.pdf",
    "solutionPdf": "SUAPC_2021s_Solution.pdf",
    "scoreboard": ["https://www.acmicpc.net/contest/spotboard/678"],
    "posterImage": "SUAPC_2021s_Poster.png"
  },
  "contest": [
    {
      "contestName": null,
      "awards": [
        {
          "rank": 1,
          "solved": 8,
          "teamName": "또또 나만 모르는 웰노운 낸다",
          "school": "서강대학교",
          "member": ["강효규", "이상원", "조원빈"]
        },
        {
          "rank": 2,
          "solved": 8,
          "teamName": "스파르타Rebro클럽",
          "school": "서강대학교",
          "member": ["박재형", "오재석", "진상우"]
        },
        {
          "rank": 3,
          "solved": 8,
          "teamName": "Order of One",
          "school": "연세대학교",
          "member": ["김기현", "김종민", "정호용"]
        },
        {
          "rank": 4,
          "solved": 8,
          "teamName": "투머치코더",
          "school": "연세대학교",
          "member": ["김형진", "동용훈", "이승재"]
        },
        {
          "rank": 5,
          "solved": 7,
          "teamName": "생수",
          "school": "홍익대학교",
          "member": ["김기선", "김효원", "정재현"]
        },
        {
          "rank": 6,
          "solved": 6,
          "teamName": "우승못하면2학기휴학함",
          "school": "홍익대학교",
          "member": ["권찬", "김도현", "박건휘"]
        },
        {
          "rank": 7,
          "solved": 5,
          "teamName": "상금 못 받으면 회식 못해요 ㅠㅠ",
          "school": "서강대학교",
          "member": ["김정모", "김준우", "박준서"]
        },
        {
          "rank": 8,
          "solved": 5,
          "teamName": "philmath12",
          "school": "서강대학교",
          "member": ["김민형", "이호현", "한상필"]
        },
        {
          "rank": 9,
          "solved": 5,
          "teamName": "ECM",
          "school": "서강대학교",
          "member": ["권지은", "김성현", "김창민"]
        },
        {
          "rank": 10,
          "solved": 5,
          "teamName": "재국이와 아이둘",
          "school": "서강대학교",
          "member": ["조유화", "조재국", "한덕규"]
        }
      ],
      "problemList": [
        {
          "problemTitle": "휴먼 파이프라인",
          "link": "https://www.acmicpc.net/problem/22981",
          "setter": {
            "name": "전해성",
            "school": "서강대학교",
            "bojHandle": "seastar105"
          }
        },
        {
          "problemTitle": "선인장의 독립집합",
          "link": "https://www.acmicpc.net/problem/22982",
          "setter": {
            "name": "이국렬",
            "school": "연세대학교",
            "bojHandle": "lky7674"
          }
        },
        {
          "problemTitle": "조각 체스판",
          "link": "https://www.acmicpc.net/problem/22983",
          "setter": {
            "name": "박수현",
            "school": "서강대학교",
            "bojHandle": "shiftpsh"
          }
        },
        {
          "problemTitle": "반짝반짝 2",
          "link": "https://www.acmicpc.net/problem/22984",
          "setter": {
            "name": "이국렬",
            "school": "연세대학교",
            "bojHandle": "lky7674"
          }
        },
        {
          "problemTitle": "문자열 조작의 달인",
          "link": "https://www.acmicpc.net/problem/22985",
          "setter": {
            "name": "김규진",
            "school": "서강대학교",
            "bojHandle": "snrnsidy"
          }
        },
        {
          "problemTitle": "Flat Earth",
          "link": "https://www.acmicpc.net/problem/22986",
          "setter": {
            "name": "전해성",
            "school": "서강대학교",
            "bojHandle": "seastar105"
          }
        },
        {
          "problemTitle": "기지국 업그레이드",
          "link": "https://www.acmicpc.net/problem/22987",
          "setter": {
            "name": "이혜아",
            "school": "KAIST",
            "bojHandle": "ho94949"
          }
        },
        {
          "problemTitle": "재활용 캠페인",
          "link": "https://www.acmicpc.net/problem/22988",
          "setter": {
            "name": "이혜아",
            "school": "KAIST",
            "bojHandle": "ho94949"
          }
        },
        {
          "problemTitle": "브런치북",
          "link": "https://www.acmicpc.net/problem/22989",
          "setter": {
            "name": "이혜아",
            "school": "KAIST",
            "bojHandle": "ho94949"
          }
        },
        {
          "problemTitle": "사이클",
          "link": "https://www.acmicpc.net/problem/22990",
          "setter": {
            "name": "이국렬",
            "school": "연세대학교",
            "bojHandle": "lky7674"
          }
        },
        {
          "problemTitle": "수요응답형 버스",
          "link": "https://www.acmicpc.net/problem/22991",
          "setter": {
            "name": "김규진",
            "school": "서강대학교",
            "bojHandle": "snrnsidy"
          }
        },
        {
          "problemTitle": "다꾸",
          "link": "https://www.acmicpc.net/problem/22992",
          "setter": {
            "name": "박수현",
            "school": "서강대학교",
            "bojHandle": "shiftpsh"
          }
        }
      ]
    }
  ],
  "setter": [
    {
      "name": "김규진",
      "school": "서강대학교",
      "bojHandle": "snrnsidy"
    },
    {
      "name": "박수현",
      "school": "서강대학교",
      "bojHandle": "shiftpsh"
    },
    {
      "name": "이국렬",
      "school": "연세대학교",
      "bojHandle": "lky7674"
    },
    {
      "name": "이혜아",
      "school": "KAIST",
      "bojHandle": "ho94949"
    },
    {
      "name": "전해성",
      "school": "서강대학교",
      "bojHandle": "seastar105"
    }
  ],
  "reviewer": [
    {
      "name": "김채완",
      "school": "선린인터넷고등학교",
      "bojHandle": "amsminn"
    },
    {
      "name": "김태영",
      "school": "KAIST",
      "bojHandle": "tae826"
    },
    {
      "name": "정치훈",
      "school": "인하대학교",
      "bojHandle": "wjdclgns12"
    },
    {
      "name": "정현서",
      "school": "서울대학교",
      "bojHandle": "jhwest2"
    },
    {
      "name": "홍은기",
      "school": "삼성전자",
      "bojHandle": "pichulia"
    }
  ],
  "sponsor": [
    {
      "id": "kakao",
      "name": "카카오"
    },
    {
      "id": "autoever",
      "name": "현대오토에버"
    },
    {
      "id": "naver-d2",
      "name": "NAVER D2"
    },
    {
      "id": "furiosa",
      "name": "퓨리오사"
    },
    {
      "id": "hanbit",
      "name": "한빛미디어"
    },
    {
      "id": "youngjin",
      "name": "영진닷컴"
    },
    {
      "id": "easyspub",
      "name": "이지스퍼블리싱"
    },
    {
      "id": "startlink",
      "name": "스타트링크"
    },
    {
      "id": "solvedac",
      "name": "솔브드"
    }
  ]
}

=== icpc-sinchon/icpc-sinchon-workspace/libs/data/suapc/2026-Winter.json
{
  "$schema": "./schema.json",
  "year": 2026,
  "season": "Winter",
  "dateTime": "2026년 2월 20일(금) 오후 1시 ~ 오후 6시",
  "note": "수상자 명단, 문제 목록, solved 수, 출제진/검수진과 주요 링크를 반영했습니다.",
  "links": {
    "problemPdf": "https://drive.google.com/file/d/1QoJUiu5ArbjzVlAgbnEV0S2P10Gek5oo/view?usp=drive_link",
    "solutionPdf": "https://upload.acmicpc.net/048d8f44-4571-4209-b06b-1ce5479742ad/",
    "scoreboard": [
      "https://www.acmicpc.net/contest/spotboard/1648"
    ],
    "posterImage": "https://drive.google.com/file/d/1MIKrfTFqplCEbN1OVc-V5gV7tmLfZ2_v/view?usp=drive_link"
  },
  "contest": [
    {
      "contestName": null,
      "awards": [
        {
          "rank": 1,
          "solved": 11,
          "teamName": "Ice Cream Pizza Crust",
          "school": "연세대학교",
          "member": [
            "정용진",
            "아세안",
            "김태윤"
          ]
        },
        {
          "rank": 2,
          "solved": 9,
          "teamName": "placeholder",
          "school": "숙명여자대학교, 연세대학교",
          "member": [
            "길수민",
            "민상원",
            "박경욱"
          ]
        },
        {
          "rank": 3,
          "solved": 9,
          "teamName": "원내생진료실",
          "school": "연세대학교",
          "member": [
            "박동언",
            "민지홍",
            "한재윤"
          ]
        },
        {
          "rank": 4,
          "solved": 8,
          "teamName": "도리도리도리",
          "school": "이화여자대학교, 홍익대학교",
          "member": [
            "박지은",
            "신정화",
            "김도현"
          ]
        },
        {
          "rank": 5,
          "solved": 8,
          "teamName": "물로켓세개를모으면하늘을날수있을까",
          "school": "서강대학교",
          "member": [
            "박준우",
            "김태윤",
            "이재찬"
          ]
        },
        {
          "rank": 6,
          "solved": 8,
          "teamName": "성북구 카르텔",
          "school": "연세대학교, 홍익대학교",
          "member": [
            "류상겸",
            "전승민",
            "권현우"
          ]
        },
        {
          "rank": 7,
          "solved": 8,
          "teamName": "니 코드 쩔더라",
          "school": "연세대학교",
          "member": [
            "최우현",
            "이협",
            "이도훈"
          ]
        },
        {
          "rank": 8,
          "solved": 7,
          "teamName": "Emdgane",
          "school": "연세대학교",
          "member": [
            "장주원",
            "권상우",
            "임예찬"
          ]
        },
        {
          "rank": 9,
          "solved": 7,
          "teamName": "규웅혁",
          "school": "서강대학교",
          "member": [
            "강효규",
            "양제웅",
            "이재혁"
          ]
        },
        {
          "rank": 10,
          "solved": 6,
          "teamName": "424",
          "school": "서강대학교",
          "member": [
            "천우영",
            "김다은",
            "손기령"
          ]
        }
      ],
      "problemList": [
        {
          "problemTitle": "유림이와 하람이의 두쫀쿠 대작전",
          "link": "https://www.acmicpc.net/problem/35277",
          "setter": {
            "name": "강호현",
            "school": "연세대학교",
            "bojHandle": "annieho"
          }
        },
        {
          "problemTitle": "수열 정렬 수수께끼",
          "link": "https://www.acmicpc.net/problem/35278",
          "setter": {
            "name": "유상혁",
            "school": "LG CNS",
            "bojHandle": "golazcc83"
          }
        },
        {
          "problemTitle": "숫자 놀이 3",
          "link": "https://www.acmicpc.net/problem/35279",
          "setter": {
            "name": "곽우석",
            "school": "SK하이닉스",
            "bojHandle": "bubbler"
          }
        },
        {
          "problemTitle": "Yet Another Binary Problem",
          "link": "https://www.acmicpc.net/problem/35280",
          "setter": {
            "name": "-",
            "school": "-",
            "bojHandle": "pyb1031"
          }
        },
        {
          "problemTitle": "가지가지",
          "link": "https://www.acmicpc.net/problem/35281",
          "setter": {
            "name": "이창민",
            "school": "강원과학고등학교",
            "bojHandle": "js7777"
          }
        },
        {
          "problemTitle": "트리와 쿼리 24",
          "link": "https://www.acmicpc.net/problem/35282",
          "setter": {
            "name": "김유담",
            "school": "경기과학고등학교",
            "bojHandle": "realpsdoingdamyoo"
          }
        },
        {
          "problemTitle": "히스토그램에서의 거리와 가장 가까운 점",
          "link": "https://www.acmicpc.net/problem/35283",
          "setter": {
            "name": "박예성",
            "school": "한양대학교",
            "bojHandle": "mythofys"
          }
        },
        {
          "problemTitle": "신촌 방수 계획",
          "link": "https://www.acmicpc.net/problem/35284",
          "setter": {
            "name": "김도윤",
            "school": "서울과학고등학교",
            "bojHandle": "kdy40929"
          }
        },
        {
          "problemTitle": "별동대",
          "link": "https://www.acmicpc.net/problem/35285",
          "setter": {
            "name": "이현서",
            "school": "한국디지털미디어고등학교",
            "bojHandle": "ibasic"
          }
        },
        {
          "problemTitle": "별동대 (Hard)",
          "link": "https://www.acmicpc.net/problem/35294",
          "setter": {
            "name": "이현서",
            "school": "한국디지털미디어고등학교",
            "bojHandle": "ibasic"
          }
        },
        {
          "problemTitle": "지하철! 지하철! 몇호선? 몇호선?",
          "link": "https://www.acmicpc.net/problem/35286",
          "setter": {
            "name": "강호현",
            "school": "연세대학교",
            "bojHandle": "annieho"
          }
        },
        {
          "problemTitle": "MC 히페리온",
          "link": "https://www.acmicpc.net/problem/35287",
          "setter": {
            "name": "김지호",
            "school": "연세대학교",
            "bojHandle": "wlgh7407"
          }
        },
        {
          "problemTitle": "Designant.",
          "link": "https://www.acmicpc.net/problem/35288",
          "setter": {
            "name": "정시우",
            "school": "서울대학교",
            "bojHandle": "sorohue"
          }
        },
        {
          "problemTitle": "괄호 문자열 카드",
          "link": "https://www.acmicpc.net/problem/35289",
          "setter": {
            "name": "유상혁",
            "school": "LG CNS",
            "bojHandle": "golazcc83"
          }
        }
      ]
    }
  ],
  "setter": [
    {
      "name": "강호현",
      "school": "연세대학교",
      "bojHandle": "annieho"
    },
    {
      "name": "유상혁",
      "school": "LG CNS",
      "bojHandle": "golazcc83"
    },
    {
      "name": "곽우석",
      "school": "SK하이닉스",
      "bojHandle": "bubbler"
    },
    {
      "name": "-",
      "school": "-",
      "bojHandle": "pyb1031"
    },
    {
      "name": "이창민",
      "school": "강원과학고등학교",
      "bojHandle": "js7777"
    },
    {
      "name": "김유담",
      "school": "경기과학고등학교",
      "bojHandle": "realpsdoingdamyoo"
    },
    {
      "name": "박예성",
      "school": "한양대학교",
      "bojHandle": "mythofys"
    },
    {
      "name": "김도윤",
      "school": "서울과학고등학교",
      "bojHandle": "kdy40929"
    },
    {
      "name": "이현서",
      "school": "한국디지털미디어고등학교",
      "bojHandle": "ibasic"
    },
    {
      "name": "김지호",
      "school": "연세대학교",
      "bojHandle": "wlgh7407"
    },
    {
      "name": "정시우",
      "school": "서울대학교",
      "bojHandle": "sorohue"
    }
  ],
  "reviewer": [
    {
      "name": "이지언",
      "school": "연세대학교",
      "bojHandle": "ez_code"
    },
    {
      "name": "윤지호",
      "school": "연세대학교",
      "bojHandle": "gs22059"
    },
    {
      "name": "이현서",
      "school": "한국디지털미디어고등학교",
      "bojHandle": "ibasic"
    },
    {
      "name": "박진한",
      "school": "고려대학교",
      "bojHandle": "jinhan814"
    },
    {
      "name": "이창민",
      "school": "강원과학고등학교",
      "bojHandle": "js7777"
    },
    {
      "name": "전준우",
      "school": "포항공과대학교",
      "bojHandle": "junwoojune"
    },
    {
      "name": "김도윤",
      "school": "서울과학고등학교",
      "bojHandle": "kdy40929"
    },
    {
      "name": "박예성",
      "school": "한양대학교",
      "bojHandle": "mythofys"
    },
    {
      "name": "김유담",
      "school": "경기과학고등학교",
      "bojHandle": "realpsdoingdamyoo"
    },
    {
      "name": "정시우",
      "school": "서울대학교",
      "bojHandle": "sorohue"
    },
    {
      "name": "장현우",
      "school": "KT",
      "bojHandle": "changhw"
    },
    {
      "name": "이국렬",
      "school": "연세대학교, Samsung Research",
      "bojHandle": "lky7674"
    },
    {
      "name": "김건표",
      "school": "서울대학교",
      "bojHandle": "denniskim"
    },
    {
      "name": "-",
      "school": "-",
      "bojHandle": "pyb1031"
    }
  ],
  "sponsor": [
    {
      "id": "goldenrabbit",
      "name": "골든래빗"
    },
    {
      "id": "youngjin",
      "name": "영진닷컴"
    },
    {
      "id": "easyspub",
      "name": "이지스퍼블리싱"
    },
    {
      "id": "insight",
      "name": "인사이트"
    },
    {
      "id": "ineasy",
      "name": "인이지"
    },
    {
      "id": "jpub",
      "name": "제이펍"
    },
    {
      "id": "chaekman",
      "name": "책만"
    },
    {
      "id": "hanbit",
      "name": "한빛미디어"
    },
    {
      "id": "aiderx",
      "name": "AiderX"
    },
    {
      "id": "jetbrains",
      "name": "JetBrains"
    },
    {
      "id": "samsung_sw",
      "name": "S/W멤버십"
    },
    {
      "id": "vessel-ai",
      "name": "Vessel AI"
    }
  ],
  "personalSponsor": [
    {
      "id": "cubic",
      "name": "cubic"
    },
    {
      "id": "nflight11",
      "name": "nflight11"
    },
    {
      "id": "김건표",
      "name": "김건표"
    },
    {
      "id": "pjshwa",
      "name": "pjshwa"
    },
    {
      "id": "woojin042",
      "name": "woojin042"
    },
    {
      "id": "오유림",
      "name": "오유림"
    },
    {
      "id": "oh040411",
      "name": "oh040411"
    }
  ]
}
