=== icpc-sinchon/icpc-sinchon-workspace/libs/data/campContest/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "title": "캠프 콘테스트",
  "description": "신촌연합 알고리즘 캠프의 캠프 콘테스트 기록을 담은 데이터 스키마",
  "properties": {
    "year": {
      "type": "integer",
      "description": "알고리즘 캠프가 진행된 연도",
      "minimum": 2019
    },
    "season": {
      "type": "string",
      "description": "알고리즘 캠프가 진행된 계절(여름, 겨울 중 하나)",
      "enum": ["Winter", "Summer"]
    },
    "dateTime": {
      "type": "string",
      "description": "캠프 콘테스트가 진행된 날짜와 시간"
    },
    "note": {
      "type": "string",
      "description": "캠프 콘테스트에 관련된 사항. 이때 특별했던 이슈 등을 기록(problemPicker 문제 선정자의 존재 등)"
    },
    "links": {
      "type": "object",
      "description": "캠프 콘테스트 관련 링크",
      "properties": {
        "problemBojLink": {
          "type": "string",
          "description": "캠프 콘테스트의 문제 BOJ 링크"
        },
        "solutionPdf": {
          "type": "string",
          "description": "캠프 콘테스트의 솔루션 PDF 링크"
        },
        "scoreboard": {
          "type": "array",
          "description": "캠프 콘테스트의 스코어보드 링크. 첫번째는 초급, 두번째는 중급...",
          "items": {
            "type": "string",
            "description": "캠프 콘테스트의 스코어보드 링크"
          },
          "minItems": 1,
          "maxItems": 3
        }
      }
    },
    "contest": {
      "type": "array",
      "description": "캠프 콘테스트의 정보",
      "items": {
        "type": "object",
        "properties": {
          "level": {
            "type": "string",
            "description": "캠프 콘테스트의 난이도",
            "enum": ["초급", "중급", "고급"]
          },
          "contestName": {
            "type": "string",
            "description": "중간고사, 기말고사 등 캠프 콘테스트의 별칭"
          },
          "problemPicker": {
            "type": "array",
            "description": "문제 선정자. 신촌연합 초기에는 콘테스트가 백준에서 문제를 뽑아 진행되었는데 이때 문제를 선정한 사람들",
            "items": {
              "type": "object",
              "description": "문제 선정자의 정보",
              "properties": {
                "name": {
                  "type": "string",
                  "description": "문제 선정자의 이름"
                },
                "school": {
                  "type": "string",
                  "description": "문제 선정자의 소속 학교"
                }
              },
              "required": ["name", "school"]
            }
          },
          "awards": {
            "type": "array",
            "description": "캠프 콘테스트의 수상자들",
            "items": {
              "type": "object",
              "description": "수상자의 정보",
              "properties": {
                "rank": {
                  "type": "integer",
                  "description": "수상 순위",
                  "minimum": 1
                },
                "name": {
                  "type": "string",
                  "description": "수상자의 이름"
                },
                "school": {
                  "type": "string",
                  "description": "수상자의 소속 학교"
                },
                "bojHandle": {
                  "type": "string",
                  "description": "수상자의 BOJ 핸들"
                }
              },
              "required": ["rank", "name", "school", "bojHandle"]
            }
          },
          "problemList": {
            "type": "array",
            "description": "캠프 콘테스트의 문제 리스트",
            "items": {
              "type": "object",
              "properties": {
                "problemTitle": {
                  "type": "string",
                  "description": "문제 제목"
                },
                "link": {
                  "type": "string",
                  "description": "문제의 BOJ 링크"
                },
                "setter": {
                  "type": "object",
                  "description": "문제 출제자",
                  "properties": {
                    "name": {
                      "type": "string",
                      "description": "문제 출제자의 이름"
                    },
                    "school": {
                      "type": "string",
                      "description": "문제 출제자의 소속 학교"
                    },
                    "bojHandle": {
                      "type": "string",
                      "description": "문제 출제자의 BOJ 핸들"
                    }
                  },
                  "required": ["name", "school", "bojHandle"]
                }
              },
              "required": ["problemTitle", "link", "setter"]
            }
          }
        }
      }
    }
  }
}

=== icpc-sinchon/icpc-sinchon-workspace/libs/data/campContest/2023-Summer.json
{
  "$schema": "./schema.json",
  "year": 2023,
  "season": "Summer",
  "dateTime": "2023년 8월 20일 오후 12시 ~ 오후 5시",
  "links": {
    "solutionPdf": "2023_ICPC_Sinchon_Summer_Algorithm_Camp_Contest_Solution.pdf",
    "problemBojLink": "https://www.acmicpc.net/category/909",
    "scoreboard": [
      "https://www.acmicpc.net/contest/spotboard/1101",
      "https://www.acmicpc.net/contest/spotboard/1102"
    ]
  },
  "contest": [
    {
      "level": "초급",
      "contestName": "Camp Contest",
      "awards": [
        {
          "rank": 1,
          "name": "김현서",
          "school": "서강대",
          "bojHandle": "alzflost"
        },
        {
          "rank": 2,
          "name": "변미담",
          "school": "서강대",
          "bojHandle": "midamida"
        },
        {
          "rank": 3,
          "name": "임정연",
          "school": "서강대",
          "bojHandle": "aprilfo01s"
        }
      ],
      "problemList": [
        {
          "problemTitle": "Toe Jumps",
          "link": "https://www.acmicpc.net/problem/28463",
          "setter": {
            "name": "정회윤",
            "school": "서강대",
            "bojHandle": "yunny_world"
          }
        },
        {
          "problemTitle": "Potato",
          "link": "https://www.acmicpc.net/problem/28464",
          "setter": {
            "name": "채성우",
            "school": "서강대",
            "bojHandle": "lem0nad3"
          }
        },
        {
          "problemTitle": "피보나치 사각형",
          "link": "https://www.acmicpc.net/problem/28465",
          "setter": {
            "name": "이협",
            "school": "연세대",
            "bojHandle": "dlguq0107"
          }
        },
        {
          "problemTitle": "좋은 팀이란?",
          "link": "https://www.acmicpc.net/problem/28466",
          "setter": {
            "name": "길수민",
            "school": "숙명여대",
            "bojHandle": "2093ab"
          }
        },
        {
          "problemTitle": "Spell Cards",
          "link": "https://www.acmicpc.net/problem/28467",
          "setter": {
            "name": "채성우",
            "school": "서강대",
            "bojHandle": "lem0nad3"
          }
        },
        {
          "problemTitle": "납이야 나비야",
          "link": "https://www.acmicpc.net/problem/28468",
          "setter": {
            "name": "최우현",
            "school": "연세대",
            "bojHandle": "starwh03"
          }
        },
        {
          "problemTitle": "Equilibrium Points",
          "link": "https://www.acmicpc.net/problem/28469",
          "setter": {
            "name": "정회윤",
            "school": "서강대",
            "bojHandle": "yunny_world"
          }
        }
      ]
    },
    {
      "level": "중급",
      "contestName": "Camp Contest",
      "awards": [
        {
          "rank": 1,
          "name": "박건휘",
          "school": "연세대",
          "bojHandle": "pgggggggggh"
        },
        {
          "rank": 2,
          "name": "한승준",
          "school": "홍익대",
          "bojHandle": "dosawas"
        },
        {
          "rank": 3,
          "name": "김태현",
          "school": "연세대",
          "bojHandle": "kth7493"
        }
      ],
      "problemList": [
        {
          "problemTitle": "슥~빡! 빡~슥!",
          "link": "https://www.acmicpc.net/problem/28470",
          "setter": {
            "name": "정회윤",
            "school": "서강대",
            "bojHandle": "yunny_world"
          }
        },
        {
          "problemTitle": "W키가 빠진 성원이",
          "link": "https://www.acmicpc.net/problem/28471",
          "setter": {
            "name": "이도훈",
            "school": "연세대",
            "bojHandle": "dhlee1031"
          }
        },
        {
          "problemTitle": "Minimax Tree",
          "link": "https://www.acmicpc.net/problem/28472",
          "setter": {
            "name": "길수민",
            "school": "숙명여대",
            "bojHandle": "2093ab"
          }
        },
        {
          "problemTitle": "도로 위의 표지판",
          "link": "https://www.acmicpc.net/problem/28473",
          "setter": {
            "name": "이도훈",
            "school": "연세대",
            "bojHandle": "dhlee1031"
          }
        },
        {
          "problemTitle": "피보나치 서로소",
          "link": "https://www.acmicpc.net/problem/28474",
          "setter": {
            "name": "이협",
            "school": "연세대",
            "bojHandle": "dlguq0107"
          }
        },
        {
          "problemTitle": "편광판",
          "link": "https://www.acmicpc.net/problem/28475",
          "setter": {
            "name": "최우현",
            "school": "연세대",
            "bojHandle": "starwh03"
          }
        },
        {
          "problemTitle": "나비야 나비야",
          "link": "https://www.acmicpc.net/problem/28476",
          "setter": {
            "name": "채성우",
            "school": "서강대",
            "bojHandle": "lem0nad3"
          }
        }
      ]
    }
  ]
}

=== icpc-sinchon/icpc-sinchon-workspace/libs/data/campContest/2022-Summer.json
{
  "$schema": "./schema.json",
  "year": 2021,
  "season": "Summer",
  "dateTime": "2022년 8월 21일 오후 1시 ~ 오후 5시",
  "links": {
    "solutionPdf": "22s-Camp-Contest-Solution.pdf",
    "problemBojLink": "https://www.acmicpc.net/category/798",
    "scoreboard": [
      "https://www.acmicpc.net/contest/spotboard/841",
      "https://www.acmicpc.net/contest/spotboard/842"
    ]
  },
  "contest": [
    {
      "level": "초급",
      "contestName": "Camp Contest",
      "awards": [
        {
          "rank": 1,
          "name": "박정빈",
          "school": "서강대",
          "bojHandle": "jeongbin"
        },
        {
          "rank": 2,
          "name": "김영빈",
          "school": "홍익대",
          "bojHandle": "bins9903"
        },
        {
          "rank": 3,
          "name": "이준석",
          "school": "서강대",
          "bojHandle": "junlee1216"
        },
        {
          "rank": 4,
          "name": "이지은",
          "school": "홍익대",
          "bojHandle": "leeju1013"
        },
        {
          "rank": 4,
          "name": "장유빈",
          "school": "서강대",
          "bojHandle": "youvebeen"
        }
      ],
      "problemList": [
        {
          "problemTitle": "단순한 문제 (Small)",
          "link": "https://www.acmicpc.net/problem/25494",
          "setter": {
            "name": "신용명",
            "school": "한양대",
            "bojHandle": "tlsdydaud1"
          }
        },
        {
          "problemTitle": "에어팟",
          "link": "https://www.acmicpc.net/problem/25495",
          "setter": {
            "name": "임민수",
            "school": "서원대",
            "bojHandle": "lms0806"
          }
        },
        {
          "problemTitle": "장신구 명장 임스",
          "link": "https://www.acmicpc.net/problem/25496",
          "setter": {
            "name": "임민수",
            "school": "서원대",
            "bojHandle": "lms0806"
          }
        },
        {
          "problemTitle": "기술 연계마스터 임스",
          "link": "https://www.acmicpc.net/problem/25497",
          "setter": {
            "name": "임민수",
            "school": "서원대",
            "bojHandle": "lms0806"
          }
        },
        {
          "problemTitle": "핸들 뭘로 하지",
          "link": "https://www.acmicpc.net/problem/25498",
          "setter": {
            "name": "이상원",
            "school": "삼성전자",
            "bojHandle": "gumgood"
          }
        },
        {
          "problemTitle": "Tipover Transform",
          "link": "https://www.acmicpc.net/problem/25499",
          "setter": {
            "name": "신용명",
            "school": "한양대",
            "bojHandle": "tlsdydaud1"
          }
        },
        {
          "problemTitle": "무자비한 최단 경로",
          "link": "https://www.acmicpc.net/problem/25500",
          "setter": {
            "name": "강효규",
            "school": "서강대",
            "bojHandle": "djs100201"
          }
        }
      ]
    },
    {
      "level": "중급",
      "contestName": "Camp Contest",
      "awards": [
        {
          "rank": 1,
          "name": "김동건",
          "school": "서강대",
          "bojHandle": "dong_gas"
        },
        {
          "rank": 2,
          "name": "정회윤",
          "school": "서강대",
          "bojHandle": "yunny_world"
        },
        {
          "rank": 3,
          "name": "정호용",
          "school": "연세대",
          "bojHandle": "portal3046"
        },
        {
          "rank": 4,
          "name": "이협",
          "school": "연세대",
          "bojHandle": "dlguq0107"
        },
        {
          "rank": 5,
          "name": "김종민",
          "school": "연세대",
          "bojHandle": "luciaholic"
        }
      ],
      "problemList": [
        {
          "problemTitle": "단순한 문제 (Large)",
          "link": "https://www.acmicpc.net/problem/25487",
          "setter": {
            "name": "신용명",
            "school": "한양대",
            "bojHandle": "tlsdydaud1"
          }
        },
        {
          "problemTitle": "토큰",
          "link": "https://www.acmicpc.net/problem/25488",
          "setter": {
            "name": "신용명",
            "school": "한양대",
            "bojHandle": "tlsdydaud1"
          }
        },
        {
          "problemTitle": "반짝반짝 3",
          "link": "https://www.acmicpc.net/problem/25489",
          "setter": {
            "name": "이국렬",
            "school": "연세대",
            "bojHandle": "lky7674"
          }
        },
        {
          "problemTitle": "수열의 점수",
          "link": "https://www.acmicpc.net/problem/25490",
          "setter": {
            "name": "이상원",
            "school": "삼성전자",
            "bojHandle": "gumgood"
          }
        },
        {
          "problemTitle": "Mexor tree",
          "link": "https://www.acmicpc.net/problem/25491",
          "setter": {
            "name": "강효규",
            "school": "서강대",
            "bojHandle": "djs100201"
          }
        },
        {
          "problemTitle": "전깃줄 연결",
          "link": "https://www.acmicpc.net/problem/25492",
          "setter": {
            "name": "이상원",
            "school": "삼성전자",
            "bojHandle": "gumgood"
          }
        },
        {
          "problemTitle": "까다로운 형제",
          "link": "https://www.acmicpc.net/problem/25493",
          "setter": {
            "name": "이상원",
            "school": "삼성전자",
            "bojHandle": "gumgood"
          }
        }
      ]
    }
  ]
}

=== icpc-sinchon/icpc-sinchon-workspace/libs/data/campContest/2021-Winter.json
{
  "$schema": "./schema.json",
  "year": 2021,
  "season": "Winter",
  "dateTime": "2021년 2월 20일 오후 1시 ~ 오후 5시",
  "links": {
    "problemBojLink": "https://www.acmicpc.net/category/795",
    "solutionPdf": "2021W-SinchonCamp-solutions.pdf",
    "scoreboard": [
      "https://www.acmicpc.net/contest/spotboard/588",
      "https://www.acmicpc.net/contest/spotboard/589"
    ]
  },
  "contest": [
    {
      "level": "초급",
      "contestName": "Camp Contest",
      "awards": [
        {
          "rank": 1,
          "name": "강민서",
          "school": "연세대",
          "bojHandle": "namoo"
        },
        {
          "rank": 2,
          "name": "정영우",
          "school": "연세대",
          "bojHandle": "existrei01"
        },
        {
          "rank": 3,
          "name": "오재석",
          "school": "서강대",
          "bojHandle": "whitehorse"
        }
      ],
      "problemList": [
        {
          "problemTitle": "영단어 암기는 괴로워",
          "link": "https://www.acmicpc.net/problem/20920",
          "setter": {
            "name": "김도은",
            "school": "숙명여대",
            "bojHandle": "whaeun25"
          }
        },
        {
          "problemTitle": "그렇고 그런 사이",
          "link": "https://www.acmicpc.net/problem/20921",
          "setter": {
            "name": "정기웅",
            "school": "연세대",
            "bojHandle": "QuqqU"
          }
        },
        {
          "problemTitle": "겹치는 건 싫어",
          "link": "https://www.acmicpc.net/problem/20922",
          "setter": {
            "name": "김도현",
            "school": "홍익대",
            "bojHandle": "swoon"
          }
        },
        {
          "problemTitle": "숫자 할리갈리 게임",
          "link": "https://www.acmicpc.net/problem/20923",
          "setter": {
            "name": "김도은",
            "school": "숙명여대",
            "bojHandle": "whaeun25"
          }
        },
        {
          "problemTitle": "트리의 기둥과 가지",
          "link": "https://www.acmicpc.net/problem/20924",
          "setter": {
            "name": "백성익",
            "school": "홍익대",
            "bojHandle": "906bc"
          }
        },
        {
          "problemTitle": "메이플스토리",
          "link": "https://www.acmicpc.net/problem/20925",
          "setter": {
            "name": "이상원",
            "school": "서강대",
            "bojHandle": "gumgood"
          }
        },
        {
          "problemTitle": "얼음 미로",
          "link": "https://www.acmicpc.net/problem/20926",
          "setter": {
            "name": "백성익",
            "school": "홍익대",
            "bojHandle": "906bc"
          }
        },
        {
          "problemTitle": "Degree Bounded Minimum Spanning Tree",
          "link": "https://www.acmicpc.net/problem/20927",
          "setter": {
            "name": "이국렬",
            "school": "연세대",
            "bojHandle": "lky7674"
          }
        }
      ]
    },
    {
      "level": "중급",
      "contestName": "Camp Contest",
      "awards": [
        {
          "rank": 1,
          "name": "조원빈",
          "school": "서강대",
          "bojHandle": "wbcho0504"
        },
        {
          "rank": 2,
          "name": "박재형",
          "school": "서강대",
          "bojHandle": "pjh6792"
        },
        {
          "rank": 3,
          "name": "남유진",
          "school": "연세대",
          "bojHandle": "youx"
        }
      ],
      "problemList": [
        {
          "problemTitle": "그렇고 그런 사이",
          "link": "https://www.acmicpc.net/problem/20921",
          "setter": {
            "name": "정기웅",
            "school": "연세대",
            "bojHandle": "QuqqU"
          }
        },
        {
          "problemTitle": "걷는 건 귀찮아",
          "link": "https://www.acmicpc.net/problem/20928",
          "setter": {
            "name": "김주현",
            "school": "서강대",
            "bojHandle": "woonikim"
          }
        },
        {
          "problemTitle": "중간",
          "link": "https://www.acmicpc.net/problem/20929",
          "setter": {
            "name": "이국렬",
            "school": "연세대",
            "bojHandle": "lky7674"
          }
        },
        {
          "problemTitle": "우주 정거장",
          "link": "https://www.acmicpc.net/problem/20930",
          "setter": {
            "name": "이국렬",
            "school": "연세대",
            "bojHandle": "lky7674"
          }
        },
        {
          "problemTitle": "혹 떼러 갔다 혹 붙여 온다",
          "link": "https://www.acmicpc.net/problem/20931",
          "setter": {
            "name": "정연두",
            "school": "홍익대",
            "bojHandle": "Green55"
          }
        },
        {
          "problemTitle": "약수 의식",
          "link": "https://www.acmicpc.net/problem/20932",
          "setter": {
            "name": "정연두",
            "school": "홍익대",
            "bojHandle": "Green55"
          }
        },
        {
          "problemTitle": "마스크펑크 2077",
          "link": "https://www.acmicpc.net/problem/20933",
          "setter": {
            "name": "김주현",
            "school": "서강대",
            "bojHandle": "woonikim"
          }
        },
        {
          "problemTitle": "카드 모래성",
          "link": "https://www.acmicpc.net/problem/20934",
          "setter": {
            "name": "김주현",
            "school": "서강대",
            "bojHandle": "woonikim"
          }
        },
        {
          "problemTitle": "Parity Constraint Perfect Matching",
          "link": "https://www.acmicpc.net/problem/20935",
          "setter": {
            "name": "이국렬",
            "school": "연세대",
            "bojHandle": "lky7674"
          }
        }
      ]
    }
  ]
}
