=== icpc-sinchon/icpc-sinchon-workspace/libs/data/campContest/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "title": "캠프 콘테스트",
  "description": "신촌연합 알고리즘 캠프의 캠프 콘테스트 기록을 담은 데이터 스키마",
  "properties": {
    "year": {
      "type": "integer",
      "description": "알고리즘 캠프가 진행된 연도",
      "minimum": 2019
    },
    "season": {
      "type": "string",
      "description": "알고리즘 캠프가 진행된 계절(여름, 겨울 중 하나)",
      "enum": ["Winter", "Summer"]
    },
    "dateTime": {
      "type": "string",
      "description": "캠프 콘테스트가 진행된 날짜와 시간"
    },
    "note": {
      "type": "string",
      "description": "캠프 콘테스트에 관련된 사항. 이때 특별했던 이슈 등을 기록(problemPicker 문제 선정자의 존재 등)"
    },
    "links": {
      "type": "object",
      "description": "캠프 콘테스트 관련 링크",
      "properties": {
        "problemBojLink": {
          "type": "string",
          "description": "캠프 콘테스트의 문제 BOJ 링크"
        },
        "solutionPdf": {
          "type": "string",
          "description": "캠프 콘테스트의 솔루션 PDF 링크"
        },
        "scoreboard": {
          "type": "array",
          "description": "캠프 콘테스트의 스코어보드 링크. 첫번째는 초급, 두번째는 중급...",
          "items": {
            "type": "string",
            "description": "캠프 콘테스트의 스코어보드 링크"
          },
          "minItems": 1,
          "maxItems": 3
        }
      }
    },
    "contest": {
      "type": "array",
      "description": "캠프 콘테스트의 정보",
      "items": {
        "type": "object",
        "properties": {
          "level": {
            "type": "string",
            "description": "캠프 콘테스트의 난이도",
            "enum": ["초급", "중급", "고급"]
          },
          "contestName": {
            "type": "string",
            "description": "중간고사, 기말고사 등 캠프 콘테스트의 별칭"
          },
          "problemPicker": {
            "type": "array",
            "description": "문제 선정자. 신촌연합 초기에는 콘테스트가 백준에서 문제를 뽑아 진행되었는데 이때 문제를 선정한 사람들",
            "items": {
              "type": "object",
              "description": "문제 선정자의 정보",
              "properties": {
                "name": {
                  "type": "string",
                  "description": "문제 선정자의 이름"
                },
                "school": {
                  "type": "string",
                  "description": "문제 선정자의 소속 학교"
                }
              },
              "required": ["name", "school"]
            }
          },
          "awards": {
            "type": "array",
            "description": "캠프 콘테스트의 수상자들",
            "items": {
              "type": "object",
              "description": "수상자의 정보",
              "properties": {
                "rank": {
                  "type": "integer",
                  "description": "수상 순위",
                  "minimum": 1
                },
                "name": {
                  "type": "string",
                  "description": "수상자의 이름"
                },
                "school": {
                  "type": "string",
                  "description": "수상자의 소속 학교"
                },
                "bojHandle": {
                  "type": "string",
                  "description": "수상자의 BOJ 핸들"
                }
              },
              "required": ["rank", "name", "school", "bojHandle"]
            }
          },
          "problemList": {
            "type": "array",
            "description": "캠프 콘테스트의 문제 리스트",
            "items": {
              "type": "object",
              "properties": {
                "problemTitle": {
                  "type": "string",
                  "description": "문제 제목"
                },
                "link": {
                  "type": "string",
                  "description": "문제의 BOJ 링크"
                },
                "setter": {
                  "type": "object",
                  "description": "문제 출제자",
                  "properties": {
                    "name": {
                      "type": "string",
                      "description": "문제 출제자의 이름"
                    },
                    "school": {
                      "type": "string",
                      "description": "문제 출제자의 소속 학교"
                    },
                    "bojHandle": {
                      "type": "string",
                      "description": "문제 출제자의 BOJ 핸들"
                    }
                  },
                  "required": ["name", "school", "bojHandle"]
                }
              },
              "required": ["problemTitle", "link", "setter"]
            }
          }
        }
      }
    }
  }
}

=== icpc-sinchon/icpc-sinchon-workspace/libs/data/campContest/2022-Winter.json
{
  "$schema": "./schema.json",
  "year": 2022,
  "season": "Winter",
  "dateTime": "2022년 2월 19일 오후 1시 ~ 오후 5시",
  "links": {
    "solutionPdf": "22w-Camp-Contest-Solution.pdf",
    "problemBojLink": "https://www.acmicpc.net/category/797",
    "scoreboard": [
      "https://www.acmicpc.net/contest/spotboard/759",
      "https://www.acmicpc.net/contest/spotboard/758"
    ]
  },
  "contest": [
    {
      "level": "초급",
      "contestName": "Camp Contest",
      "awards": [
        {
          "rank": 1,
          "name": "이준하",
          "school": "서강대",
          "bojHandle": "imearth01"
        },
        {
          "rank": 2,
          "name": "이지은",
          "school": "홍익대",
          "bojHandle": "leeju1013"
        },
        {
          "rank": 3,
          "name": "김연웅",
          "school": "연세대",
          "bojHandle": "sodapop95"
        }
      ],
      "problemList": [
        {
          "problemTitle": "시간복잡도를 배운 도도",
          "link": "https://www.acmicpc.net/problem/24510",
          "setter": {
            "name": "김도현",
            "school": "홍익대",
            "bojHandle": "swoon"
          }
        },
        {
          "problemTitle": "상품의 주인은?",
          "link": "https://www.acmicpc.net/problem/24509",
          "setter": {
            "name": "송혜민",
            "school": "숙명여대",
            "bojHandle": "songfox00"
          }
        },
        {
          "problemTitle": "queuestack",
          "link": "https://www.acmicpc.net/problem/24511",
          "setter": {
            "name": "김도현",
            "school": "홍익대",
            "bojHandle": "swoon"
          }
        },
        {
          "problemTitle": "Bottleneck Travelling Salesman Problem (Small)",
          "link": "https://www.acmicpc.net/problem/24512",
          "setter": {
            "name": "이국렬",
            "school": "연세대",
            "bojHandle": "lky7674"
          }
        },
        {
          "problemTitle": "좀비 바이러스",
          "link": "https://www.acmicpc.net/problem/24513",
          "setter": {
            "name": "송혜민",
            "school": "숙명여대",
            "bojHandle": "songfox00"
          }
        },
        {
          "problemTitle": "n번째 숫자 찾기",
          "link": "https://www.acmicpc.net/problem/24514",
          "setter": {
            "name": "박준성",
            "school": "서강대",
            "bojHandle": "wnstjd13245"
          }
        },
        {
          "problemTitle": "히히 못가",
          "link": "https://www.acmicpc.net/problem/24515",
          "setter": {
            "name": "이상원",
            "school": "서강대",
            "bojHandle": "gumgood"
          }
        }
      ]
    },
    {
      "level": "중급",
      "contestName": "Camp Contest",
      "awards": [
        {
          "rank": 1,
          "name": "김태윤",
          "school": "연세대",
          "bojHandle": "ystaeyoon113"
        },
        {
          "rank": 2,
          "name": "김정모",
          "school": "서강대",
          "bojHandle": "meque98"
        },
        {
          "rank": 3,
          "name": "박준서",
          "school": "서강대",
          "bojHandle": "p_jun"
        }
      ],
      "problemList": [
        {
          "problemTitle": "잘 알려진 수열 구하기",
          "link": "https://www.acmicpc.net/problem/24516",
          "setter": {
            "name": "강효규",
            "school": "서강대",
            "bojHandle": "djs100201"
          }
        },
        {
          "problemTitle": "잘 알려진 합 구하기",
          "link": "https://www.acmicpc.net/problem/24518",
          "setter": {
            "name": "강효규",
            "school": "서강대",
            "bojHandle": "djs100201"
          }
        },
        {
          "problemTitle": "카드 게임과 쿼리",
          "link": "https://www.acmicpc.net/problem/24517",
          "setter": {
            "name": "김도현",
            "school": "홍익대",
            "bojHandle": "swoon"
          }
        },
        {
          "problemTitle": "Bottleneck Travelling Salesman Problem (Large)",
          "link": "https://www.acmicpc.net/problem/24519",
          "setter": {
            "name": "이국렬",
            "school": "연세대",
            "bojHandle": "lky7674"
          }
        },
        {
          "problemTitle": "Meet In The Middle",
          "link": "https://www.acmicpc.net/problem/24520",
          "setter": {
            "name": "이상원",
            "school": "서강대",
            "bojHandle": "gumgood"
          }
        },
        {
          "problemTitle": "스네이크 게임",
          "link": "https://www.acmicpc.net/problem/24522",
          "setter": {
            "name": "이상원",
            "school": "서강대",
            "bojHandle": "gumgood"
          }
        },
        {
          "problemTitle": "토지 구입",
          "link": "https://www.acmicpc.net/problem/24521",
          "setter": {
            "name": "이국렬",
            "school": "연세대",
            "bojHandle": "lky7674"
          }
        }
      ]
    }
  ]
}

=== icpc-sinchon/icpc-sinchon-workspace/libs/data/campContest/2021-Summer.json
{
  "$schema": "./schema.json",
  "year": 2021,
  "season": "Summer",
  "dateTime": "2021년 8월 21일 오후 2시 ~ 오후 5시",
  "links": {
    "problemBojLink": "https://www.acmicpc.net/category/796",
    "solutionPdf": "21s-Camp-Contest-Solutions.zip",
    "scoreboard": [
      "https://www.acmicpc.net/contest/spotboard/676",
      "https://www.acmicpc.net/contest/spotboard/677"
    ]
  },
  "contest": [
    {
      "level": "초급",
      "contestName": "Camp Contest",
      "awards": [
        {
          "rank": 1,
          "name": "김창민",
          "school": "서강대",
          "bojHandle": "jakads"
        },
        {
          "rank": 2,
          "name": "전재현",
          "school": "연세대",
          "bojHandle": "chrisj67"
        },
        {
          "rank": 3,
          "name": "김성현",
          "school": "서강대",
          "bojHandle": "dart"
        }
      ],
      "problemList": [
        {
          "problemTitle": "이진수 나눗셈",
          "link": "https://www.acmicpc.net/problem/22950",
          "setter": {
            "name": "김도은",
            "school": "숙명여대",
            "bojHandle": "whaeun25"
          }
        },
        {
          "problemTitle": "송이의 카드 게임",
          "link": "https://www.acmicpc.net/problem/22951",
          "setter": {
            "name": "송혜민",
            "school": "숙명여대",
            "bojHandle": "songfox00"
          }
        },
        {
          "problemTitle": "permutation making",
          "link": "https://www.acmicpc.net/problem/22952",
          "setter": {
            "name": "강효규",
            "school": "서강대",
            "bojHandle": "djs100201"
          }
        },
        {
          "problemTitle": "도도의 음식 준비",
          "link": "https://www.acmicpc.net/problem/22953",
          "setter": {
            "name": "김도현",
            "school": "홍익대",
            "bojHandle": "swoon"
          }
        },
        {
          "problemTitle": "그래프 트리 분할",
          "link": "https://www.acmicpc.net/problem/22954",
          "setter": {
            "name": "강효규",
            "school": "서강대",
            "bojHandle": "djs100201"
          }
        },
        {
          "problemTitle": "고양이 도도의 탈출기",
          "link": "https://www.acmicpc.net/problem/22955",
          "setter": {
            "name": "김도은",
            "school": "숙명여대",
            "bojHandle": "whaeun25"
          }
        },
        {
          "problemTitle": "소나기",
          "link": "https://www.acmicpc.net/problem/22956",
          "setter": {
            "name": "김도현",
            "school": "홍익대",
            "bojHandle": "swoon"
          }
        }
      ]
    },
    {
      "level": "중급",
      "contestName": "Camp Contest",
      "awards": [
        {
          "rank": 1,
          "name": "조원빈",
          "school": "서강대",
          "bojHandle": "wbcho0504"
        },
        {
          "rank": 2,
          "name": "김종민",
          "school": "연세대",
          "bojHandle": "luciaholic"
        },
        {
          "rank": 3,
          "name": "김기현",
          "school": "연세대",
          "bojHandle": "surface_03"
        }
      ],
      "problem_list": [
        {
          "problemTitle": "permutation making",
          "link": "https://www.acmicpc.net/problem/22952",
          "setter": {
            "name": "강효규",
            "school": "서강대",
            "bojHandle": "djs100201"
          }
        },
        {
          "problemTitle": "짝수싫어수",
          "link": "https://www.acmicpc.net/problem/22957",
          "setter": {
            "name": "김도현",
            "school": "홍익대",
            "bojHandle": "swoon"
          }
        },
        {
          "problemTitle": "안산 탐지기",
          "link": "https://www.acmicpc.net/problem/22958",
          "setter": {
            "name": "이국렬",
            "school": "연세대",
            "bojHandle": "lky7674"
          }
        },
        {
          "problemTitle": "신촌의 수열과 쿼리",
          "link": "https://www.acmicpc.net/problem/22959",
          "setter": {
            "name": "강효규",
            "school": "서강대",
            "bojHandle": "djs100201"
          }
        },
        {
          "problemTitle": "미팅",
          "link": "https://www.acmicpc.net/problem/22960",
          "setter": {
            "name": "이국렬",
            "school": "연세대",
            "bojHandle": "lky7674"
          }
        },
        {
          "problemTitle": "여행사 운영하기",
          "link": "https://www.acmicpc.net/problem/22961",
          "setter": {
            "name": "전해성",
            "school": "서강대",
            "bojHandle": "seastar105"
          }
        },
        {
          "problemTitle": "신촌방위본부",
          "link": "https://www.acmicpc.net/problem/22962",
          "setter": {
            "name": "이국렬",
            "school": "연세대",
            "bojHandle": "lky7674"
          }
        }
      ]
    }
  ]
}

=== icpc-sinchon/icpc-sinchon-workspace/libs/data/campContest/2020 Summer.json
{
  "$schema": "./schema.json",
  "year": 2020,
  "season": "Summer",
  "dateTime": "2020년 8월 31일 오후 2시 ~ 오후 5시",
  "note": "2020년 신촌연합에서 진행된 ICPC Sinchon 2020 Summer Camp Contest입니다. 처음으로 문제를 새로 출제하여 진행되었습니다.",
  "links": {
    "problemBojLink": "https://www.acmicpc.net/category/794",
    "solutionPdf": "ICPC_Sinchon_2020_Summer_Camp_Contest.pdf",
    "scoreboard": [
      "https://www.acmicpc.net/contest/board/532",
      "https://www.acmicpc.net/contest/board/533"
    ]
  },
  "contest": [
    {
      "level": "초급",
      "contestName": "중간고사",
      "problemPicker": [
        {
          "name": "이길원",
          "school": "서강대학교"
        },
        {
          "name": "전해성",
          "school": "서강대학교"
        },
        {
          "name": "남수연",
          "school": "숙명여자대학교"
        }
      ],
      "awards": [
        {
          "rank": 1,
          "name": "김태윤",
          "school": "연세대",
          "bojHandle": "ystaeyoon113"
        },
        {
          "rank": 2,
          "name": "김도현",
          "school": "홍익대학교",
          "bojHandle": "swoon"
        },
        {
          "rank": 3,
          "name": "윤이빈",
          "school": "숙명여대",
          "bojHandle": "yibin99"
        }
      ]
    },
    {
      "level": "초급",
      "contestName": "기말고사",
      "awards": [
        {
          "rank": 1,
          "name": "김태윤",
          "school": "연세대",
          "bojHandle": "ystaeyoon113"
        },
        {
          "rank": 2,
          "name": "김도현",
          "school": "홍익대학교",
          "bojHandle": "swoon"
        },
        {
          "rank": 3,
          "name": "김경민",
          "school": "홍익대학교",
          "bojHandle": "kgmin604"
        }
      ],
      "problemList": [
        {
          "problemTitle": "요요 시뮬레이션",
          "link": "https://www.acmicpc.net/problem/19636",
          "setter": {
            "name": "백성익",
            "school": "홍익대학교",
            "bojHandle": "906bc"
          }
        },
        {
          "problemTitle": "IF문 좀 대신 써줘",
          "link": "https://www.acmicpc.net/problem/19637",
          "setter": {
            "name": "백성익",
            "school": "홍익대학교",
            "bojHandle": "906bc"
          }
        },
        {
          "problemTitle": "센티와 마법의 뿅망치",
          "link": "https://www.acmicpc.net/problem/19638",
          "setter": {
            "name": "백성익",
            "school": "홍익대학교",
            "bojHandle": "906bc"
          }
        },
        {
          "problemTitle": "화장실의 규칙",
          "link": "https://www.acmicpc.net/problem/19640",
          "setter": {
            "name": "백성익",
            "school": "홍익대학교",
            "bojHandle": "906bc"
          }
        },
        {
          "problemTitle": "중첩 집합 모델",
          "link": "https://www.acmicpc.net/problem/19641",
          "setter": {
            "name": "이재열",
            "school": "홍익대학교",
            "bojHandle": "malkoring"
          }
        },
        {
          "problemTitle": "TORIE",
          "link": "https://www.acmicpc.net/problem/19642",
          "setter": {
            "name": "백성익",
            "school": "홍익대학교",
            "bojHandle": "906bc"
          }
        },
        {
          "problemTitle": "좀비 떼가 전역 때보다 먼저 오다니",
          "link": "https://www.acmicpc.net/problem/19643",
          "setter": {
            "name": "백성익",
            "school": "홍익대학교",
            "bojHandle": "906bc"
          }
        },
        {
          "problemTitle": "좀비 떼가 기관총 진지에도 오다니",
          "link": "https://www.acmicpc.net/problem/19644",
          "setter": {
            "name": "백성익",
            "school": "홍익대학교",
            "bojHandle": "906bc"
          }
        }
      ]
    },
    {
      "level": "중급",
      "contestName": "중간고사",
      "problemPicker": [
        {
          "name": "이기현",
          "school": "서강대"
        },
        {
          "name": "최재민",
          "school": "KAIST"
        }
      ],
      "awards": [
        {
          "rank": 1,
          "name": "박재형",
          "school": "서강대",
          "bojHandle": "pjh6792"
        },
        {
          "rank": 2,
          "name": "남유진",
          "school": "연세대",
          "bojHandle": "youx"
        },
        {
          "rank": 3,
          "name": "박준성",
          "school": "서강대",
          "bojHandle": "wnstjd13245"
        }
      ]
    },
    {
      "level": "중급",
      "contestName": "기말고사",
      "awards": [
        {
          "rank": 1,
          "name": "김관우",
          "school": "서강대",
          "bojHandle": "rhksdn6227"
        },
        {
          "rank": 2,
          "name": "남유진",
          "school": "연세대",
          "bojHandle": "youx"
        },
        {
          "rank": 3,
          "name": "이승은",
          "school": "서강대",
          "bojHandle": "leese0425"
        }
      ],
      "problemList": [
        {
          "problemTitle": "센티와 마법의 뿅망치",
          "link": "https://www.acmicpc.net/problem/19638",
          "setter": {
            "name": "백성익",
            "school": "홍익대학교",
            "bojHandle": "906bc"
          }
        },
        {
          "problemTitle": "배틀로얄",
          "link": "https://www.acmicpc.net/problem/19639",
          "setter": {
            "name": "이준석",
            "school": "서강대학교",
            "bojHandle": "semteo04"
          }
        },
        {
          "problemTitle": "햄최몇?",
          "link": "https://www.acmicpc.net/problem/19645",
          "setter": {
            "name": "임지환",
            "school": "서강대학교",
            "bojHandle": "raararaara"
          }
        },
        {
          "problemTitle": "Random Generator",
          "link": "https://www.acmicpc.net/problem/19646",
          "setter": {
            "name": "이국렬",
            "school": "연세대",
            "bojHandle": "lky7674"
          }
        },
        {
          "problemTitle": "Unique Solution",
          "link": "https://www.acmicpc.net/problem/19647",
          "setter": {
            "name": "이국렬",
            "school": "연세대",
            "bojHandle": "lky7674"
          }
        },
        {
          "problemTitle": "미하일 2마리",
          "link": "https://www.acmicpc.net/problem/19648",
          "setter": {
            "name": "이국렬",
            "school": "연세대",
            "bojHandle": "lky7674"
          }
        },
        {
          "problemTitle": "미담 전하기",
          "link": "https://www.acmicpc.net/problem/19649",
          "setter": {
            "name": "임지환",
            "school": "서강대",
            "bojHandle": "raararaara"
          }
        },
        {
          "problemTitle": "개미여행",
          "link": "https://www.acmicpc.net/problem/19650",
          "setter": {
            "name": "이준석",
            "school": "서강대",
            "bojHandle": "semteo04"
          }
        }
      ]
    }
  ]
}

=== icpc-sinchon/icpc-sinchon-workspace/libs/data/campContest/2020-Winter.json
{
  "$schema": "./schema.json",
  "year": 2020,
  "season": "Winter",
  "dateTime": "2020년 2월 2일 오후 2시 ~ 오후 5시",
  "note": "신촌연합에서 처음으로 진행된 캠프 콘테스트입니다. 알고리즘 캠프의 성취도를 확인하는 목적으로 중간고사와 기말고사가 진행되었으며 문제를 새로 출제하는 대신 BOJ의 문제를 선정하는 방식이었습니다.",
  "contest": [
    {
      "level": "초급",
      "contestName": "중간고사",
      "problemPicker": [
        {
          "name": "이태한",
          "school": "서강대"
        },
        {
          "name": "이재열",
          "school": "홍익대"
        },
        {
          "name": "김성민",
          "school": "홍익대"
        }
      ],
      "awards": [
        {
          "rank": 1,
          "name": "강상원",
          "school": "서강대",
          "bojHandle": "kevink1113"
        },
        {
          "rank": 2,
          "name": "주상민",
          "school": "서강대",
          "bojHandle": "jsm3465"
        },
        {
          "rank": 3,
          "name": "윤상현",
          "school": "서강대",
          "bojHandle": "tkdgus0782"
        }
      ]
    },
    {
      "level": "초급",
      "contestName": "기말고사",
      "problemPicker": [
        {
          "name": "이태한",
          "school": "서강대"
        },
        {
          "name": "이재열",
          "school": "홍익대"
        },
        {
          "name": "김성민",
          "school": "홍익대"
        },
        {
          "name": "정연두",
          "school": "홍익대"
        }
      ],
      "awards": [
        {
          "rank": 1,
          "name": "강상원",
          "school": "서강대",
          "bojHandle": "kevink1113"
        },
        {
          "rank": 2,
          "name": "주상민",
          "school": "서강대",
          "bojHandle": "jsm3465"
        },
        {
          "rank": 3,
          "name": "임세홍",
          "school": "서강대",
          "bojHandle": "sehjong1602"
        }
      ]
    },
    {
      "level": "중급",
      "contestName": "중간고사",
      "problemPicker": [
        {
          "name": "임지환",
          "school": "서강대"
        },
        {
          "name": "이기현",
          "school": "서강대"
        }
      ],
      "awards": [
        {
          "rank": 1,
          "name": "백성익",
          "school": "홍익대",
          "bojHandle": "906bc"
        },
        {
          "rank": 2,
          "name": "정재현",
          "school": "홍익대",
          "bojHandle": "dicohy27"
        },
        {
          "rank": 3,
          "name": "강승구",
          "school": "서강대",
          "bojHandle": "v010309"
        }
      ]
    },
    {
      "level": "중급",
      "contestName": "기말고사",
      "problemPicker": [
        {
          "name": "임지환",
          "school": "서강대"
        },
        {
          "name": "이기현",
          "school": "서강대"
        }
      ],
      "awards": [
        {
          "rank": 1,
          "name": "장주호",
          "school": "서강대",
          "bojHandle": "jayjangjooho"
        },
        {
          "rank": 2,
          "name": "백성익",
          "school": "홍익대",
          "bojHandle": "906bc"
        },
        {
          "rank": 3,
          "name": "정재현",
          "school": "홍익대",
          "bojHandle": "dicohy27"
        }
      ]
    }
  ]
}

=== icpc-sinchon/icpc-sinchon-workspace/libs/data/campContest/2023-Winter.json
{
  "$schema": "./schema.json",
  "year": 2023,
  "season": "Winter",
  "dateTime": "2023년 2월 18일 오후 12시 ~ 오후 5시",
  "links": {
    "problemBojLink": "https://www.acmicpc.net/category/801",
    "solutionPdf": "2023_ICPC_Sinchon_Winter_Algorithm_Camp_Contest_Solution.pdf",
    "scoreboard": [
      "https://www.acmicpc.net/contest/spotboard/947",
      "https://www.acmicpc.net/contest/spotboard/948"
    ]
  },
  "contest": [
    {
      "level": "초급",
      "contestName": "Camp Contest",
      "awards": [
        {
          "rank": 1,
          "name": "김기철",
          "school": "서강대",
          "bojHandle": "gi9410"
        },
        {
          "rank": 2,
          "name": "이형민",
          "school": "홍익대",
          "bojHandle": "kurage3822"
        },
        {
          "rank": 3,
          "name": "채문혁",
          "school": "연세대",
          "bojHandle": "chaemh2013"
        }
      ],
      "problemList": [
        {
          "problemTitle": "2023년은 검은 토끼의 해",
          "link": "https://www.acmicpc.net/problem/27494",
          "setter": {
            "name": "김범수",
            "school": "홍익대",
            "bojHandle": "starbow"
          }
        },
        {
          "problemTitle": "만다라트 만들기",
          "link": "https://www.acmicpc.net/problem/27495",
          "setter": {
            "name": "강다혜",
            "school": "서강대",
            "bojHandle": "psst54"
          }
        },
        {
          "problemTitle": "발머의 피크 이론",
          "link": "https://www.acmicpc.net/problem/27496",
          "setter": {
            "name": "손기령",
            "school": "서강대",
            "bojHandle": "lickelon"
          }
        },
        {
          "problemTitle": "알파벳 블록",
          "link": "https://www.acmicpc.net/problem/27497",
          "setter": {
            "name": "김범수",
            "school": "홍익대",
            "bojHandle": "starbow"
          }
        },
        {
          "problemTitle": "연애 혁명",
          "link": "https://www.acmicpc.net/problem/27498",
          "setter": {
            "name": "손기령",
            "school": "서강대",
            "bojHandle": "lickelon"
          }
        },
        {
          "problemTitle": "레이저 쏘기",
          "link": "https://www.acmicpc.net/problem/27499",
          "setter": {
            "name": "유호영",
            "school": "서강대",
            "bojHandle": "tkfkddl59323"
          }
        },
        {
          "problemTitle": "이 게임에서 진정한 탑은 누구인가",
          "link": "https://www.acmicpc.net/problem/27500",
          "setter": {
            "name": "김성민",
            "school": "홍익대",
            "bojHandle": "tolelom"
          }
        }
      ]
    },
    {
      "level": "중급",
      "contestName": "Camp Contest",
      "awards": [
        {
          "rank": 1,
          "name": "이승형",
          "school": "서강대",
          "bojHandle": "tmdgud0617"
        },
        {
          "rank": 2,
          "name": "채성우",
          "school": "서강대",
          "bojHandle": "lem0nad3"
        },
        {
          "rank": 3,
          "name": "한승준",
          "school": "홍익대",
          "bojHandle": "dosawas"
        }
      ],
      "problemList": [
        {
          "problemTitle": "RGB트리",
          "link": "https://www.acmicpc.net/problem/27501",
          "setter": {
            "name": "곽재혁",
            "school": "연세대",
            "bojHandle": "dreami63"
          }
        },
        {
          "problemTitle": "천국의 계단",
          "link": "https://www.acmicpc.net/problem/27505",
          "setter": {
            "name": "유호영",
            "school": "서강대",
            "bojHandle": "tkfkddl59323"
          }
        },
        {
          "problemTitle": "가난한 고흐와 붓",
          "link": "https://www.acmicpc.net/problem/27502",
          "setter": {
            "name": "김태윤",
            "school": "연세대",
            "bojHandle": "ystaeyoon113"
          }
        },
        {
          "problemTitle": "요가 수업",
          "link": "https://www.acmicpc.net/problem/27503",
          "setter": {
            "name": "김성현",
            "school": "서강대",
            "bojHandle": "dart"
          }
        },
        {
          "problemTitle": "상대음감의 노래찾기",
          "link": "https://www.acmicpc.net/problem/27504",
          "setter": {
            "name": "손기령",
            "school": "서강대",
            "bojHandle": "lickelon"
          }
        },
        {
          "problemTitle": "함수열과 쿼리",
          "link": "https://www.acmicpc.net/problem/27506",
          "setter": {
            "name": "유호영",
            "school": "서강대",
            "bojHandle": "tkfkddl59323"
          }
        },
        {
          "problemTitle": "K볼록껍질",
          "link": "https://www.acmicpc.net/problem/27507",
          "setter": {
            "name": "곽재혁",
            "school": "연세대",
            "bojHandle": "dreami63"
          }
        }
      ]
    }
  ]
}
